apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Full Lifecycle
    operators.operatorframework.io/builder: operator-sdk-v1.0.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: extendeddaemonset.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ExtendedDaemonSetReplicaSet is the Schema for the extendeddaemonsetreplicasets API.
      displayName: Extended Daemon Set Replica Set
      kind: ExtendedDaemonSetReplicaSet
      name: extendeddaemonsetreplicasets.datadoghq.com
      version: v1alpha1
    - description: ExtendedDaemonSet is the Schema for the extendeddaemonsets API.
      displayName: Extended Daemon Set
      kind: ExtendedDaemonSet
      name: extendeddaemonsets.datadoghq.com
      version: v1alpha1
    - description: ExtendedDaemonsetSetting is the Schema for the extendeddaemonsetsettings API.
      displayName: Extended Daemonset Setting
      kind: ExtendedDaemonsetSetting
      name: extendeddaemonsetsettings.datadoghq.com
      version: v1alpha1
  description: |-
    ExtendedDaemonSet aims to provide a new implementation of the Kubernetes DaemonSet resource with key features:
      * Canary Deployment: Deploy a new DaemonSet version with only a few nodes.
      * Custom Rolling Update: Improve the default rolling update logic available in Kubernetes batch/v1 Daemonset.
  displayName: extendeddaemonset
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - Daemonset
  - Canary
  - ExtendedDaemonset
  - Deployment
  links:
  - name: Documentation
    url: https://github.com/DataDog/extendeddaemonset
  maintainers:
  - email: cedric@datadoghq.com
    name: Cedric Lamoriniere
  maturity: alpha
  provider:
    name: Datadog
    url: https://github.com/DataDog/extendeddaemonset
  version: 0.0.0
