apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  features:
    apm:
      enabled: true
  global:
    clusterName: my-example-cluster
    credentials:
      apiKey: ENC[api_key]
      appKey: ENC[app_key]
  override:
    clusterAgent:
      containers:
        cluster-agent:
          env:
            - name: DD_SECRET_BACKEND_COMMAND
              value: "/readsecret.sh"
            - name: DD_SECRET_BACKEND_ARGUMENTS
              value: "/etc/secret-volume"
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/secret-volume
      volumes:
        - name: secret-volume
          secret:
            secretName: test-secret
    nodeAgent:
      env:
        - name: DD_SECRET_BACKEND_COMMAND
          value: "/readsecret.sh"
        - name: DD_SECRET_BACKEND_ARGUMENTS
          value: "/etc/secret-volume"
      containers:
        agent:
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/secret-volume
        process-agent:
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/secret-volume
        trace-agent:
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/secret-volume
      volumes:
        - name: secret-volume
          secret:
            secretName: test-secret
