apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  clusterName: foo
  credentials:
    apiKey: <DATADOG_API_KEY>
    appKey: <DATADOG_APP_KEY>
  features:
    orchestratorExplorer:
      enabled: true
      conf:
        configMap:
          name: orchestrator-conf
  clusterAgent:
    config:
      clusterChecksEnabled: true
  clusterChecksRunner:
    enabled: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: orchestrator-conf
data:
  pods.yaml: |-
    cluster_check: true
    init_config:
    instances:
      - collectors:
          - pods
        skip_leader_election: true
  jobs.yaml: |-
    cluster_check: true
    init_config:
    instances:
      - collectors:
          - jobs
          - cronjobs
        skip_leader_election: true
  workloads.yaml: |-
    cluster_check: true
    init_config:
    instances:
      - collectors:
          - deployments
          - replicasets
          - daemonsets
          - statefulsets
        skip_leader_election: true
  others.yaml: |-
    cluster_check: true
    init_config:
    instances:
      - collectors:
          - nodes
          - services
        skip_leader_election: true
