apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  annotations:
    experimental.agent.datadoghq.com/image-override.trace-agent: "agent:7.63.1-rc.2"
spec:
  global:
    clusterName: my-example-cluster
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
      appSecret:
        secretName: datadog-secret
        keyName: app-key
    env:
      - name: DD_HOSTNAME
        value: "local-testing"
  override:
    nodeAgent:
      image:
        tag: 7.63.1-rc.1
