apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  credentials:
    apiKey: <paste-your-api-key-here>
    appKey: <paste-your-app-key-here>
  agent:
    image:
      name: "gcr.io/datadoghq/agent:latest"
    config:
      criSocket:
        criSocketPath: /var/run/crio/crio.sock
        useCriSocketVolume: true
      env:
      - name: DD_KUBELET_TLS_VERIFY
        value: "false"
    log:
      enabled: false
  clusterAgent:
    image:
      name: "gcr.io/datadoghq/cluster-agent:latest"
    config:
      externalMetrics:
        enabled: true
        port: 5010
      clusterChecksRunnerEnabled: true
    replicas: 2
  clusterChecksRunner:
    image:
      name: "gcr.io/datadoghq/agent:latest"
