apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  features:
    orchestratorExplorer:
      enabled: true
      conf:
        configMap:
          name: orchestrator-conf
    clusterChecks:
      enabled: true
      useClusterChecksRunners: true
  global:
    credentials:
      apiKey: <DATADOG_API_KEY>
      appKey: <DATADOG_APP_KEY>
    clusterName: foo
