apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
    credentials:
      apiKey: <DATADOG_API_KEY>
  features:
    otelCollector:
      enabled: true
      ports:
        - containerPort: 4317
          name: otel-grpc
        - containerPort: 4318
          name: otel-http
      conf: 
        configData: |-
            receivers:
              otlp:
                protocols:
                  grpc:
                  http:
            exporters:
              debug:
                verbosity: detailed
              datadog:
                api:
                  key: ""
            processors:
              batch:
            connectors:
            service:
              pipelines:
                traces:
                  receivers: [otlp]
                  processors: [batch]
                  exporters: [datadog]
                metrics:
                  receivers: [otlp]
                  processors: [batch]
                  exporters: [datadog]
                logs:
                  receivers: [otlp]
                  processors: [batch]
                  exporters: [datadog]

