apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: datadog
spec:
  credentials:
    apiKey: <paste-your-api-key-here>
    appKey: <paste-your-app-key-here>
  agent:
    rbac:
      serviceAccountName: datadog-agent-scc
    config:
      securityContext:
        runAsUser: 0
        seLinuxOptions:
          level: s0
          role: system_r
          type: spc_t
          user: system_u
      criSocket:
        criSocketPath: /var/run/crio/crio.sock
    log:
      enabled: true
    apm:
      enabled: true
    process:
      enabled: true
      processCollectionEnabled: true
