apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  clusterName: foo
  credentials:
    apiKey: <DATADOG_API_KEY>
    appKey: <DATADOG_APP_KEY>
  features:
    orchestratorExplorer:
      enabled: true
    kubeStateMetricsCore:
      enabled: true
      conf:
        configMap:
          name: cluster-agent-ksm-conf
  agent:
  clusterAgent:
    config:
      clusterChecksEnabled: true
  clusterChecksRunner:
    enabled: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-agent-ksm-conf
data:
  pods.yaml: |-
    cluster_check: true
    init_config:
    instances:
      - collectors:
        - pods
  nodes.yaml: |-
    cluster_check: true
    init_config:
    instances:
      - collectors:
        - nodes
  others.yaml: |-
    cluster_check: true
    init_config:
    instances:
      - collectors:
        - secrets
        - services
        - resourcequotas
        - replicationcontrollers
        - limitranges
        - persistentvolumeclaims
        - persistentvolumes
        - namespaces
        - endpoints
        - daemonsets
        - deployments
        - replicasets
        - statefulsets
        - cronjobs
        - jobs
        - horizontalpodautoscalers
        - poddisruptionbudgets
        - storageclasses
        - volumeattachments
