apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  credentials:
    apiKey: <DATADOG_API_KEY>
    appKey: <DATADOG_APP_KEY>
  agent:
    image:
      name: "datadog/agent:7"
    apm:
      enabled: true
      unixDomainSocket:
        enabled: true
    config:
      dogstatsd:
        dogstatsdOriginDetection: true
        unixDomainSocket:
          enabled: true
