apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  credentials:
    apiKey: <DATADOG_API_KEY>
    appKey: <DATADOG_APP_KEY>
    token: <DATADOG_CLUSTER_AGENT_TOKEN>
  features:
    prometheusScrape:
      enabled: true
      serviceEndpoints: true
      additionalConfigs: |-
        - autodiscovery:
            kubernetes_annotations:
              include:
                custom_label: 'true'
            kubernetes_container_names:
            - my-app
          configurations:
          - send_distribution_buckets: true
            timeout: 5
  agent:
    image:
      name: "gcr.io/datadoghq/agent:latest"
    config:
      tolerations:
      - operator: Exists
  clusterAgent:
    image:
      name: "gcr.io/datadoghq/cluster-agent:latest"
    replicas: 2
