# datadog-agent-with-otelagentgateway.yaml
# This example shows how to enable and configure the OTel Agent Gateway component.
# The OTel Agent Gateway runs as a separate deployment and can be used
# to collect and forward OpenTelemetry data.
#
# This example demonstrates all available configuration options including:
# - Custom ConfigMap with OTel collector configuration
# - Feature-level configuration (feature gates)
# - Override configuration (replicas, resources, security contexts, node selectors, affinity, tolerations, env, etc.)

# Optional: ConfigMap with custom OTel Agent Gateway configuration
# When provided, this will be used instead of the default gateway configuration
# The ConfigMap key MUST be named "otel-gateway-config.yaml"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-otel-gateway-config
data:
  otel-gateway-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
    processors:
      batch:
        timeout: 10s
        send_batch_size: 1024
        send_batch_max_size: 2048
      # Add custom processors here, e.g., filtering, sampling, etc.
      attributes:
        actions:
          - key: deployment.environment
            value: production
            action: insert
    exporters:
      debug:
        verbosity: detailed
      datadog:
        api:
          key: ${env:DD_API_KEY}
    extensions:
      datadog:
        api:
          key: ${env:DD_API_KEY}
    service:
      extensions: [datadog]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [attributes, batch]
          exporters: [datadog, debug]
        metrics:
          receivers: [otlp]
          processors: [attributes, batch]
          exporters: [datadog, debug]
        logs:
          receivers: [otlp]
          processors: [attributes, batch]
          exporters: [datadog, debug]
---
# Optional: ConfigMap for additional environment variables
# This demonstrates using envFrom to inject environment variables into the gateway pods
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-gateway-env-config
data:
  OTEL_RESOURCE_ATTRIBUTES: "service.name=my-gateway,deployment.environment=production"
  CUSTOM_GATEWAY_SETTING: "example-value"
---
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key

  features:
    # Enable OTel Agent Gateway with feature-level configuration
    otelAgentGateway:
      enabled: true

      # Optional: Reference the custom ConfigMap created above
      # Comment this out to use the default gateway configuration
      conf:
        configMap:
          name: custom-otel-gateway-config

      # Feature gates to pass to OTel collector as a comma-separated list
      # These gates enable/disable specific features in the OpenTelemetry Collector
      featureGates: "telemetry.UseLocalHostAsDefaultMetricsAddress,logs.jsonParserArray"

  override:
    # Override configuration for fine-grained control over the OTel Agent Gateway deployment
    otelAgentGateway:
      # Number of replicas for the gateway deployment
      replicas: 2

      # Node selector to schedule gateway pods on specific nodes (commented out for local testing)
      # nodeSelector:
      #   kubernetes.io/os: linux
      #   node-type: observability

      # Affinity configuration for pod scheduling (commented out for local testing)
      # affinity:
      #   podAntiAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #     - weight: 100
      #       podAffinityTerm:
      #         labelSelector:
      #           matchExpressions:
      #           - key: app
      #             operator: In
      #             values:
      #             - datadog-otel-agent-gateway
      #         topologyKey: kubernetes.io/hostname

      # Tolerations for scheduling on tainted nodes (commented out for local testing)
      # tolerations:
      # - key: "dedicated"
      #   operator: "Equal"
      #   value: "otel-gateway"
      #   effect: "NoSchedule"

      # Priority class for pod scheduling (commented out for local testing)
      # priorityClassName: high-priority

      # Additional environment variables for all containers in this component
      env:
      - name: OTEL_LOG_LEVEL
        value: "debug"
      - name: CUSTOM_VAR
        value: "custom-value"

      # Environment variables from ConfigMaps or Secrets
      # This loads all key-value pairs from the ConfigMap as environment variables
      envFrom:
      - configMapRef:
          name: otel-gateway-env-config

      # Custom image configuration (optional)
      image:
        name: ddot-collector
        tag: "7.74.1"
        pullPolicy: IfNotPresent
      # Pod-level security context to ensure volumes are writable by non-root user
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"

      # Configure containers (both init and regular containers use the same map)
      containers:
        # Configure the init-volume init container
        init-volume:
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 200Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL

        # Configure the otel-agent container
        otel-agent:
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
          # Additional environment variables specific to this container
          env:
          - name: CONTAINER_SPECIFIC_VAR
            value: "container-value"

      # Additional labels for pods
      labels:
        team: observability
        environment: production

      # Additional annotations for pods
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8888"
