apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  credentials:
    apiKey: <DATADOG_API_KEY>
    appKey: <DATADOG_APP_KEY>
    token: <DATADOG_CLUSTER_AGENT_TOKEN>
  agent:
    image:
      name: "gcr.io/datadoghq/agent:latest"
    config:
      tolerations:
      - operator: Exists
  clusterAgent:
    image:
      name: "gcr.io/datadoghq/cluster-agent:latest"
    config:
      externalMetrics:
        enabled: true
    replicas: 2
