image: registry.ddbuild.io/images/mirror/library/golang:1.25.8
variables:
  PROJECTNAME: "datadog-operator"
  PROJECTNAME_CHECK: "datadog-operator-check"
  JOB_DOCKER_IMAGE: "registry.ddbuild.io/ci-containers-project:v68399443-88dc260-v1.22"
  RH_PARTNER_REGISTRY: "quay.io/redhat-isv-containers"
  RH_PARTNER_PROJECT_ID: "5e7c8ebc1c86a3163d1a69be"
  RH_PARTNER_REGISTRY_USER: "redhat-isv-containers+5e7c8ebc1c86a3163d1a69be-robot"
  RH_PARTNER_REGISTRY_KEY_SSM_KEY: redhat_registry_key
  RH_PARTNER_API_KEY_SSM_KEY: redhat_api_key

stages:
  - release
  - post-release

# Runs preflight checks without submitting the image
check_preflight_redhat_image:
  stage: release
  rules:
    - when: manual
  variables:
    RELEASE_TAG: "v1.25.0"
  tags:
    - "docker-in-docker:amd64"
  image: $JOB_DOCKER_IMAGE
  script:
    - apt-get update && apt-get -y install --no-install-recommends build-essential git awscli && apt-get -y clean && rm -rf /var/lib/apt/lists/*
    - aws ssm get-parameter --region us-east-1 --name ci.datadog-operator.redhat_registry_key --with-decryption --query "Parameter.Value" --out text | docker login --username "$RH_PARTNER_REGISTRY_USER" --password-stdin "$RH_PARTNER_REGISTRY"
    - export RH_PARTNER_API_TOKEN=$(aws ssm get-parameter --region us-east-1 --name ci.datadog-operator.$RH_PARTNER_API_KEY_SSM_KEY --with-decryption --query "Parameter.Value" --out text)
    - export IMG=$RH_PARTNER_REGISTRY/$RH_PARTNER_PROJECT_ID:${RELEASE_TAG:1}
    - make preflight-redhat-container

# Preflight now supports multiarch image checks
submit_preflight_redhat_image:
  stage: post-release
  allow_failure: true
  rules:
    - when: manual
  variables:
    RELEASE_TAG: "v1.25.0"
  tags:
    - "docker-in-docker:amd64"
  image: $JOB_DOCKER_IMAGE
  script:
    - apt-get update && apt-get -y install --no-install-recommends build-essential git awscli && apt-get -y clean && rm -rf /var/lib/apt/lists/*
    - aws ssm get-parameter --region us-east-1 --name ci.datadog-operator.$RH_PARTNER_REGISTRY_KEY_SSM_KEY --with-decryption --query "Parameter.Value" --out text | docker login --username "$RH_PARTNER_REGISTRY_USER" --password-stdin "$RH_PARTNER_REGISTRY"
    - export RH_PARTNER_API_TOKEN=$(aws ssm get-parameter --region us-east-1 --name ci.datadog-operator.$RH_PARTNER_API_KEY_SSM_KEY --with-decryption --query "Parameter.Value" --out text)
    - export IMG=$RH_PARTNER_REGISTRY/$RH_PARTNER_PROJECT_ID:${RELEASE_TAG:1}
    - make preflight-redhat-container-submit
