version: 2
before:
  hooks:
    - go mod download
builds:
- id: kubectl-datadog
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  env:
  - CGO_ENABLED=0
  main: ./cmd/kubectl-datadog/main.go
  ldflags: -w -X github.com/DataDog/datadog-operator/pkg/version/version.Commit=${GIT_COMMIT} -X github.com/DataDog/datadog-operator/pkg/version/version.Version=${VERSION} -X github.com/DataDog/datadog-operator/pkg/version/version.BuildTime=${DATE} -s
  binary: kubectl-datadog
archives:
- id: kubectl-datadog
  builds:
  - kubectl-datadog
  name_template: "kubectl-datadog_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  wrap_in_directory: false
  format: zip
  files:
  - LICENSE
snapshot:
  version_template: SNAPSHOT-{{ .Commit }}
checksum:
  # Algorithm to be used.
  # Accepted options are sha256, sha512, sha1, crc32, md5, sha224 and sha384.
  # Default is sha256.
  algorithm: sha256
