apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: datadog
spec:
  version: INVALID_SET_ME
  shortDescription: Manage the Datadog Operator
  description: |
    The datadog kubectl plugin provides useful utilities to operate datadog-agent components
    via the Datadog Operator and the DatadogAgent CRD.
  homepage: https://github.com/DataDog/datadog-operator
  platforms:
  - uri: https://github.com/DataDog/datadog-operator/releases/download/INVALID_SET_ME/kubectl-datadog_INVALID_SET_ME_darwin_amd64.zip
    sha256: INVALID_SET_ME
    bin: kubectl-datadog
    files:
    - from: kubectl-datadog
      to: .
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        os: darwin
        arch: amd64
  - uri: https://github.com/DataDog/datadog-operator/releases/download/INVALID_SET_ME/kubectl-datadog_INVALID_SET_ME_linux_amd64.zip
    sha256: INVALID_SET_ME
    bin: kubectl-datadog
    files:
    - from: kubectl-datadog
      to: .
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        os: linux
        arch: amd64
