
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: datadogmonitors.datadogoperator.dogwoord.com
spec:
  group: datadogoperator.dogwoord.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                existingMonitorId:
                  type: integer
                  description: The ID of the existing monitor to adopt
            status:
              type: object
              properties:
                id:
                  type: integer
                  description: The ID of the monitor
  scope: Namespaced
  names:
    plural: datadogmonitors
    singular: datadogmonitor
    kind: DatadogMonitor
    shortNames:
    - ddm
