//go:build !ignore_autogenerated

// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2016-present Datadog, Inc.

// Code generated by controller-gen. DO NOT EDIT.

package common

import (
	"k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerCondition) DeepCopyInto(out *DatadogPodAutoscalerCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerCondition.
func (in *DatadogPodAutoscalerCondition) DeepCopy() *DatadogPodAutoscalerCondition {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerConstraints) DeepCopyInto(out *DatadogPodAutoscalerConstraints) {
	*out = *in
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]DatadogPodAutoscalerContainerConstraints, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerConstraints.
func (in *DatadogPodAutoscalerConstraints) DeepCopy() *DatadogPodAutoscalerConstraints {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerConstraints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerContainerConstraints) DeepCopyInto(out *DatadogPodAutoscalerContainerConstraints) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = new(DatadogPodAutoscalerContainerResourceConstraints)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerContainerConstraints.
func (in *DatadogPodAutoscalerContainerConstraints) DeepCopy() *DatadogPodAutoscalerContainerConstraints {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerContainerConstraints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerContainerResourceConstraints) DeepCopyInto(out *DatadogPodAutoscalerContainerResourceConstraints) {
	*out = *in
	if in.MinAllowed != nil {
		in, out := &in.MinAllowed, &out.MinAllowed
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.MaxAllowed != nil {
		in, out := &in.MaxAllowed, &out.MaxAllowed
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerContainerResourceConstraints.
func (in *DatadogPodAutoscalerContainerResourceConstraints) DeepCopy() *DatadogPodAutoscalerContainerResourceConstraints {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerContainerResourceConstraints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerContainerResourceObjective) DeepCopyInto(out *DatadogPodAutoscalerContainerResourceObjective) {
	*out = *in
	in.Value.DeepCopyInto(&out.Value)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerContainerResourceObjective.
func (in *DatadogPodAutoscalerContainerResourceObjective) DeepCopy() *DatadogPodAutoscalerContainerResourceObjective {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerContainerResourceObjective)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerContainerResources) DeepCopyInto(out *DatadogPodAutoscalerContainerResources) {
	*out = *in
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerContainerResources.
func (in *DatadogPodAutoscalerContainerResources) DeepCopy() *DatadogPodAutoscalerContainerResources {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerContainerResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerControllerObjective) DeepCopyInto(out *DatadogPodAutoscalerControllerObjective) {
	*out = *in
	in.Query.DeepCopyInto(&out.Query)
	in.Value.DeepCopyInto(&out.Value)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerControllerObjective.
func (in *DatadogPodAutoscalerControllerObjective) DeepCopy() *DatadogPodAutoscalerControllerObjective {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerControllerObjective)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerHorizontalAction) DeepCopyInto(out *DatadogPodAutoscalerHorizontalAction) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
	if in.RecommendedReplicas != nil {
		in, out := &in.RecommendedReplicas, &out.RecommendedReplicas
		*out = new(int32)
		**out = **in
	}
	if in.LimitedReason != nil {
		in, out := &in.LimitedReason, &out.LimitedReason
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerHorizontalAction.
func (in *DatadogPodAutoscalerHorizontalAction) DeepCopy() *DatadogPodAutoscalerHorizontalAction {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerHorizontalAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerHorizontalRecommendation) DeepCopyInto(out *DatadogPodAutoscalerHorizontalRecommendation) {
	*out = *in
	in.GeneratedAt.DeepCopyInto(&out.GeneratedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerHorizontalRecommendation.
func (in *DatadogPodAutoscalerHorizontalRecommendation) DeepCopy() *DatadogPodAutoscalerHorizontalRecommendation {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerHorizontalRecommendation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerHorizontalStatus) DeepCopyInto(out *DatadogPodAutoscalerHorizontalStatus) {
	*out = *in
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(DatadogPodAutoscalerHorizontalRecommendation)
		(*in).DeepCopyInto(*out)
	}
	if in.LastActions != nil {
		in, out := &in.LastActions, &out.LastActions
		*out = make([]DatadogPodAutoscalerHorizontalAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastRecommendations != nil {
		in, out := &in.LastRecommendations, &out.LastRecommendations
		*out = make([]DatadogPodAutoscalerHorizontalRecommendation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerHorizontalStatus.
func (in *DatadogPodAutoscalerHorizontalStatus) DeepCopy() *DatadogPodAutoscalerHorizontalStatus {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerHorizontalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerObjective) DeepCopyInto(out *DatadogPodAutoscalerObjective) {
	*out = *in
	if in.PodResource != nil {
		in, out := &in.PodResource, &out.PodResource
		*out = new(DatadogPodAutoscalerPodResourceObjective)
		(*in).DeepCopyInto(*out)
	}
	if in.ContainerResource != nil {
		in, out := &in.ContainerResource, &out.ContainerResource
		*out = new(DatadogPodAutoscalerContainerResourceObjective)
		(*in).DeepCopyInto(*out)
	}
	if in.ControllerObjective != nil {
		in, out := &in.ControllerObjective, &out.ControllerObjective
		*out = new(DatadogPodAutoscalerControllerObjective)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerObjective.
func (in *DatadogPodAutoscalerObjective) DeepCopy() *DatadogPodAutoscalerObjective {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerObjective)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerObjectiveValue) DeepCopyInto(out *DatadogPodAutoscalerObjectiveValue) {
	*out = *in
	if in.Utilization != nil {
		in, out := &in.Utilization, &out.Utilization
		*out = new(int32)
		**out = **in
	}
	if in.AverageValue != nil {
		in, out := &in.AverageValue, &out.AverageValue
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerObjectiveValue.
func (in *DatadogPodAutoscalerObjectiveValue) DeepCopy() *DatadogPodAutoscalerObjectiveValue {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerObjectiveValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerPodResourceObjective) DeepCopyInto(out *DatadogPodAutoscalerPodResourceObjective) {
	*out = *in
	in.Value.DeepCopyInto(&out.Value)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerPodResourceObjective.
func (in *DatadogPodAutoscalerPodResourceObjective) DeepCopy() *DatadogPodAutoscalerPodResourceObjective {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerPodResourceObjective)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerScalingPolicy) DeepCopyInto(out *DatadogPodAutoscalerScalingPolicy) {
	*out = *in
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(DatadogPodAutoscalerScalingStrategySelect)
		**out = **in
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]DatadogPodAutoscalerScalingRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerScalingPolicy.
func (in *DatadogPodAutoscalerScalingPolicy) DeepCopy() *DatadogPodAutoscalerScalingPolicy {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerScalingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerScalingRule) DeepCopyInto(out *DatadogPodAutoscalerScalingRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerScalingRule.
func (in *DatadogPodAutoscalerScalingRule) DeepCopy() *DatadogPodAutoscalerScalingRule {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerScalingRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerStatus) DeepCopyInto(out *DatadogPodAutoscalerStatus) {
	*out = *in
	if in.Vertical != nil {
		in, out := &in.Vertical, &out.Vertical
		*out = new(DatadogPodAutoscalerVerticalStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Horizontal != nil {
		in, out := &in.Horizontal, &out.Horizontal
		*out = new(DatadogPodAutoscalerHorizontalStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.CurrentReplicas != nil {
		in, out := &in.CurrentReplicas, &out.CurrentReplicas
		*out = new(int32)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]DatadogPodAutoscalerCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerStatus.
func (in *DatadogPodAutoscalerStatus) DeepCopy() *DatadogPodAutoscalerStatus {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerUpdatePolicy) DeepCopyInto(out *DatadogPodAutoscalerUpdatePolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerUpdatePolicy.
func (in *DatadogPodAutoscalerUpdatePolicy) DeepCopy() *DatadogPodAutoscalerUpdatePolicy {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerUpdatePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerVerticalAction) DeepCopyInto(out *DatadogPodAutoscalerVerticalAction) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerVerticalAction.
func (in *DatadogPodAutoscalerVerticalAction) DeepCopy() *DatadogPodAutoscalerVerticalAction {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerVerticalAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerVerticalStatus) DeepCopyInto(out *DatadogPodAutoscalerVerticalStatus) {
	*out = *in
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(DatadogPodAutoscalerVerticalTargetStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.LastAction != nil {
		in, out := &in.LastAction, &out.LastAction
		*out = new(DatadogPodAutoscalerVerticalAction)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerVerticalStatus.
func (in *DatadogPodAutoscalerVerticalStatus) DeepCopy() *DatadogPodAutoscalerVerticalStatus {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerVerticalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerVerticalTargetStatus) DeepCopyInto(out *DatadogPodAutoscalerVerticalTargetStatus) {
	*out = *in
	in.GeneratedAt.DeepCopyInto(&out.GeneratedAt)
	if in.Scaled != nil {
		in, out := &in.Scaled, &out.Scaled
		*out = new(int32)
		**out = **in
	}
	if in.DesiredResources != nil {
		in, out := &in.DesiredResources, &out.DesiredResources
		*out = make([]DatadogPodAutoscalerContainerResources, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.PodCPURequest = in.PodCPURequest.DeepCopy()
	out.PodMemoryRequest = in.PodMemoryRequest.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerVerticalTargetStatus.
func (in *DatadogPodAutoscalerVerticalTargetStatus) DeepCopy() *DatadogPodAutoscalerVerticalTargetStatus {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerVerticalTargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsTimeseriesQuery) DeepCopyInto(out *MetricsTimeseriesQuery) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsTimeseriesQuery.
func (in *MetricsTimeseriesQuery) DeepCopy() *MetricsTimeseriesQuery {
	if in == nil {
		return nil
	}
	out := new(MetricsTimeseriesQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryFormula) DeepCopyInto(out *QueryFormula) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryFormula.
func (in *QueryFormula) DeepCopy() *QueryFormula {
	if in == nil {
		return nil
	}
	out := new(QueryFormula)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollingUpdate) DeepCopyInto(out *RollingUpdate) {
	*out = *in
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.MaxSurge != nil {
		in, out := &in.MaxSurge, &out.MaxSurge
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollingUpdate.
func (in *RollingUpdate) DeepCopy() *RollingUpdate {
	if in == nil {
		return nil
	}
	out := new(RollingUpdate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeseriesFormulaRequest) DeepCopyInto(out *TimeseriesFormulaRequest) {
	*out = *in
	in.Attributes.DeepCopyInto(&out.Attributes)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeseriesFormulaRequest.
func (in *TimeseriesFormulaRequest) DeepCopy() *TimeseriesFormulaRequest {
	if in == nil {
		return nil
	}
	out := new(TimeseriesFormulaRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeseriesFormulaRequestAttributes) DeepCopyInto(out *TimeseriesFormulaRequestAttributes) {
	*out = *in
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(int64)
		**out = **in
	}
	if in.Formulas != nil {
		in, out := &in.Formulas, &out.Formulas
		*out = make([]QueryFormula, len(*in))
		copy(*out, *in)
	}
	if in.Queries != nil {
		in, out := &in.Queries, &out.Queries
		*out = make([]TimeseriesQuery, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeseriesFormulaRequestAttributes.
func (in *TimeseriesFormulaRequestAttributes) DeepCopy() *TimeseriesFormulaRequestAttributes {
	if in == nil {
		return nil
	}
	out := new(TimeseriesFormulaRequestAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeseriesQuery) DeepCopyInto(out *TimeseriesQuery) {
	*out = *in
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(MetricsTimeseriesQuery)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeseriesQuery.
func (in *TimeseriesQuery) DeepCopy() *TimeseriesQuery {
	if in == nil {
		return nil
	}
	out := new(TimeseriesQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateStrategy) DeepCopyInto(out *UpdateStrategy) {
	*out = *in
	if in.RollingUpdate != nil {
		in, out := &in.RollingUpdate, &out.RollingUpdate
		*out = new(RollingUpdate)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateStrategy.
func (in *UpdateStrategy) DeepCopy() *UpdateStrategy {
	if in == nil {
		return nil
	}
	out := new(UpdateStrategy)
	in.DeepCopyInto(out)
	return out
}
