resources:
- manager.yaml
images:
- name: controller
  newName: 601427279990.dkr.ecr.us-east-1.amazonaws.com/guillermo.julian/sandbox
  newTag: operator
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
