apiVersion: datadoghq.com/v1alpha1
kind: ExtendedDaemonsetSetting
metadata:
  name: example-extendeddaemonsetsetting
spec:
  nodeSelector: 
    matchLabels:
      overwrite: foo-daemon
  reference:
    kind: ExtendedDaemonset
    name: foo
  containers:
  - name: daemon
    resources:
      requests:
        cpu: "0.1"
        memory: "30m"
