## Append samples you want in your CSV to this file as resources ##
resources:
- eds_v1alpha1_basic.yaml
- edssetting_v1alpha1_basic.yaml
- ers_v1alpha1.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
