{{- with .Values.managedAgentInstallationCredentials }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: datadog-api-key
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: eks-addon
spec:
  provider: aws
  secretObjects:
    - secretName: datadog-secret
      type: Opaque
      data:
        - objectName: api-key
          key: api-key
  parameters:
    usePodIdentity: "true"
    objects: |
      - objectName: {{ .secretsManagerSecretID | quote }}
        objectType: secretsmanager
        objectAlias: api-key
        filePermission: "0400"
{{- end }}
