{{- with .Values.managedAgentInstallation }}
{{- $intent := dict
  "version" .version
  "installationID" .installationID
  "eksARNSHA256" .eksARNSHA256
  "operationID" .operationID
  "desiredState" .desiredState
  "bootstrap" .bootstrap
-}}
{{- with .acknowledgedOperationID }}
{{- $_ := set $intent "acknowledgedOperationID" . -}}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: datadog-agent-managed-installation-intent
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: eks-addon
data:
  intent.json: |-
    {{ $intent | toJson }}
{{- end }}
