{{- $credentialsSecretSync := .Values.credentialsSecretSync | default dict -}}
{{- if or $credentialsSecretSync.apiKeySecretId $credentialsSecretSync.appKeySecretId }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: datadog-credentials
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: datadog-ascp-secret-sync
    app.kubernetes.io/managed-by: eks-addon
spec:
  provider: aws
  secretObjects:
    - secretName: {{ default "datadog-secret" $credentialsSecretSync.kubernetesSecretName | quote }}
      type: Opaque
      labels:
        app.kubernetes.io/managed-by: eks-addon
      data:
{{ if $credentialsSecretSync.apiKeySecretId }}
        - objectName: api-key
          key: api-key
{{ end }}
{{ if $credentialsSecretSync.appKeySecretId }}
        - objectName: app-key
          key: app-key
{{ end }}
  parameters:
    usePodIdentity: "true"
    objects: |
{{ if $credentialsSecretSync.apiKeySecretId }}
      - objectName: {{ $credentialsSecretSync.apiKeySecretId | quote }}
        objectType: secretsmanager
        objectAlias: api-key
        filePermission: "0400"
{{ end }}
{{ if $credentialsSecretSync.appKeySecretId }}
      - objectName: {{ $credentialsSecretSync.appKeySecretId | quote }}
        objectType: secretsmanager
        objectAlias: app-key
        filePermission: "0400"
{{ end }}
{{- end }}
