apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  features:
    apm:
      enabled: true
    otlp:
      receiver:
        protocols:
          grpc:
            enabled: true
          http:
            enabled: true
  global:
    clusterName: my-example-cluster
    credentials:
      apiKey: <DATADOG_API_KEY>
      appKey: <DATADOG_APP_KEY>
