apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: datadog
spec:
  features:
    logCollection:
      enabled: true
    liveProcessCollection:
      enabled: true
    liveContainerCollection:
      enabled: true
    apm:
      enabled: true
  global:
    credentials:
      apiKey: <DATADOG_API_KEY>
      appKey: <DATADOG_API_KEY>
    criSocketPath: /var/run/crio/crio.sock
    kubelet:
      tlsVerify: false
  override:
    nodeAgent:
      hostNetwork: true
      serviceAccountName: datadog-agent-scc
      securityContext:
        runAsUser: 0
        seLinuxOptions:
          user: system_u
          role: system_r
          type: spc_t
          level: s0
    clusterAgent:
      serviceAccountName: datadog-agent-scc
      replicas: 2