# ----------------------------------------------------------#
# An example of using an existing secret to store the  #
# Datadog credentials                                       #
# ----------------------------------------------------------#
# First, create the datadog-secret with the folling command:
# kubectl create secret generic datadog-secret --from-literal api-key=$DD_API_KEY --from-literal app-key=$DD_APP_KEY

apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
      appSecret:
        secretName: datadog-secret
        keyName: app-key
    clusterName: foo
    registry: public.ecr.aws/datadog
