apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    credentials:
      apiKey: <api-key>
    clusterName: gke-autopilot-on-kind
    kubelet:
      # This is needed if the kubelet certificate is self-signed.
      # Alternatively, the CA certificate used to sign the kubelet certificate can be mounted.
      tlsVerify: false
  features:
    apm:
      enabled: true
      hostPortConfig:
        enabled: true
        hostPort: 8126
    
      
