apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  credentials:
    apiKey: <DATADOG_API_KEY>
    appKey: <DATADOG_APP_KEY>
    token: <DATADOG_CLUSTER_AGENT_TOKEN>
  agent:
    config:
      tolerations:
      - operator: Exists
  clusterAgent:
    config:
      externalMetrics:
        enabled: true
      clusterChecksEnabled: true
    replicas: 2
  clusterChecksRunner:
    enabled: true
