apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  credentials:
    apiKey: ENC[api_key]
    appKey: ENC[app_key]
    useSecretBackend: true
  agent:
    env:
      - name: DD_SECRET_BACKEND_COMMAND
        value: "/readsecret.sh"
      - name: DD_SECRET_BACKEND_ARGUMENTS
        value: "/etc/secret-volume"
    config:
      volumes:
        - name: secret-volume
          secret:
            secretName: test-secret
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret-volume
    process:
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret-volume
    apm:
      enabled: true
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret-volume
  clusterAgent:
    enabled: true
    config:
      env:
        - name: DD_SECRET_BACKEND_COMMAND
          value: "/readsecret.sh"
        - name: DD_SECRET_BACKEND_ARGUMENTS
          value: "/etc/secret-volume"
      volumes:
        - name: secret-volume
          secret:
            secretName: test-secret
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret-volume
