apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: controller
  newName: gcr.io/datadoghq/operator
  newTag: latest
kind: Kustomization
namePrefix: datadog-operator-e2e-
namespace: system
patches:
- path: rc-e2e-manager.yaml
  target:
    kind: Deployment
    name: manager
resources:
- ../crd
- ../rbac
- e2e-manager.yaml
