apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: controller
  newName: gcr.io/datadoghq/operator
  newTag: latest
kind: Kustomization
namePrefix: datadog-operator-e2e-
namespace: e2e-operator
resources:
- ../crd
- ../rbac
- e2e-manager.yaml
