apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: system
spec:
    spec:
      containers:
        args:
        - --enable-leader-election
        - --pprof
        - --remoteConfigEnabled
        env:
        - name: DD_API_KEY
          valueFrom:
            secretKeyRef:
              name: datadog-secret
              key: api-key
        - name: DD_APP_KEY
          valueFrom:
            secretKeyRef:
              name: datadog-secret
              key: app-key
        - name: DD_CLUSTER_NAME
          value: rc-updater-e2e-test-cluster
        - name: DD_SITE
          value: datadoghq.com
