# permissions for end users to view datadogagentinternals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: datadogagentinternal-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: datadog-operator
    app.kubernetes.io/part-of: datadog-operator
    app.kubernetes.io/managed-by: kustomize
  name: datadogagentinternal-viewer-role
rules:
- apiGroups:
  - datadoghq.com
  resources:
  - datadogagentinternals
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - datadoghq.com
  resources:
  - datadogagentinternals/status
  verbs:
  - get
