# permissions for end users to edit datadoggenericresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: datadog-genericresource-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: datadog-operator
    app.kubernetes.io/part-of: datadog-operator
    app.kubernetes.io/managed-by: kustomize
  name: datadoggenericresource-editor-role
rules:
- apiGroups:
  - datadoghq.com
  resources:
  - datadoggenericresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - datadoghq.com
  resources:
  - datadoggenericresources/status
  verbs:
  - get
