resources:
- service_account.yaml
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
# The following RBAC configurations are used to protect
# the metrics endpoint with authn/authz. These configurations
# ensure that only authorized users and service accounts
# can access the metrics endpoint.
# - metrics_auth_role.yaml
# - metrics_auth_role_binding.yaml
# - metrics_reader_role.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization