//go:build !ignore_autogenerated

// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2016-present Datadog, Inc.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	"github.com/DataDog/datadog-operator/api/datadoghq/common"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogFallbackPolicy) DeepCopyInto(out *DatadogFallbackPolicy) {
	*out = *in
	in.Horizontal.DeepCopyInto(&out.Horizontal)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogFallbackPolicy.
func (in *DatadogFallbackPolicy) DeepCopy() *DatadogFallbackPolicy {
	if in == nil {
		return nil
	}
	out := new(DatadogFallbackPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscaler) DeepCopyInto(out *DatadogPodAutoscaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscaler.
func (in *DatadogPodAutoscaler) DeepCopy() *DatadogPodAutoscaler {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatadogPodAutoscaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerApplyPolicy) DeepCopyInto(out *DatadogPodAutoscalerApplyPolicy) {
	*out = *in
	if in.Update != nil {
		in, out := &in.Update, &out.Update
		*out = new(common.DatadogPodAutoscalerUpdatePolicy)
		**out = **in
	}
	if in.ScaleUp != nil {
		in, out := &in.ScaleUp, &out.ScaleUp
		*out = new(common.DatadogPodAutoscalerScalingPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.ScaleDown != nil {
		in, out := &in.ScaleDown, &out.ScaleDown
		*out = new(common.DatadogPodAutoscalerScalingPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerApplyPolicy.
func (in *DatadogPodAutoscalerApplyPolicy) DeepCopy() *DatadogPodAutoscalerApplyPolicy {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerApplyPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerHorizontalFallbackPolicy) DeepCopyInto(out *DatadogPodAutoscalerHorizontalFallbackPolicy) {
	*out = *in
	out.Triggers = in.Triggers
	if in.Objectives != nil {
		in, out := &in.Objectives, &out.Objectives
		*out = make([]common.DatadogPodAutoscalerObjective, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerHorizontalFallbackPolicy.
func (in *DatadogPodAutoscalerHorizontalFallbackPolicy) DeepCopy() *DatadogPodAutoscalerHorizontalFallbackPolicy {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerHorizontalFallbackPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerList) DeepCopyInto(out *DatadogPodAutoscalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatadogPodAutoscaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerList.
func (in *DatadogPodAutoscalerList) DeepCopy() *DatadogPodAutoscalerList {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatadogPodAutoscalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerSpec) DeepCopyInto(out *DatadogPodAutoscalerSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	if in.RemoteVersion != nil {
		in, out := &in.RemoteVersion, &out.RemoteVersion
		*out = new(uint64)
		**out = **in
	}
	if in.ApplyPolicy != nil {
		in, out := &in.ApplyPolicy, &out.ApplyPolicy
		*out = new(DatadogPodAutoscalerApplyPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Objectives != nil {
		in, out := &in.Objectives, &out.Objectives
		*out = make([]common.DatadogPodAutoscalerObjective, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Fallback != nil {
		in, out := &in.Fallback, &out.Fallback
		*out = new(DatadogFallbackPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Constraints != nil {
		in, out := &in.Constraints, &out.Constraints
		*out = new(common.DatadogPodAutoscalerConstraints)
		(*in).DeepCopyInto(*out)
	}
	if in.RecommendationOptions != nil {
		in, out := &in.RecommendationOptions, &out.RecommendationOptions
		*out = new(common.DatadogPodAutoscalerRecommendationOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerSpec.
func (in *DatadogPodAutoscalerSpec) DeepCopy() *DatadogPodAutoscalerSpec {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HorizontalFallbackTriggers) DeepCopyInto(out *HorizontalFallbackTriggers) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HorizontalFallbackTriggers.
func (in *HorizontalFallbackTriggers) DeepCopy() *HorizontalFallbackTriggers {
	if in == nil {
		return nil
	}
	out := new(HorizontalFallbackTriggers)
	in.DeepCopyInto(out)
	return out
}
