//go:build !ignore_autogenerated

// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2016-present Datadog, Inc.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/DataDog/datadog-api-client-go/v2/api/datadogV1"
	commonv1 "github.com/DataDog/datadog-operator/apis/datadoghq/common/v1"
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config) DeepCopyInto(out *Config) {
	*out = *in
	if in.Override != nil {
		in, out := &in.Override, &out.Override
		*out = make(map[ComponentName]*Override, len(*in))
		for key, val := range *in {
			var outVal *Override
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(Override)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config.
func (in *Config) DeepCopy() *Config {
	if in == nil {
		return nil
	}
	out := new(Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Container) DeepCopyInto(out *Container) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Container.
func (in *Container) DeepCopy() *Container {
	if in == nil {
		return nil
	}
	out := new(Container)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardTemplateVariable) DeepCopyInto(out *DashboardTemplateVariable) {
	*out = *in
	if in.AvailableValues != nil {
		in, out := &in.AvailableValues, &out.AvailableValues
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(string)
		**out = **in
	}
	if in.Defaults != nil {
		in, out := &in.Defaults, &out.Defaults
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardTemplateVariable.
func (in *DashboardTemplateVariable) DeepCopy() *DashboardTemplateVariable {
	if in == nil {
		return nil
	}
	out := new(DashboardTemplateVariable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardTemplateVariablePreset) DeepCopyInto(out *DashboardTemplateVariablePreset) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.TemplateVariables != nil {
		in, out := &in.TemplateVariables, &out.TemplateVariables
		*out = make([]DashboardTemplateVariablePresetValue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardTemplateVariablePreset.
func (in *DashboardTemplateVariablePreset) DeepCopy() *DashboardTemplateVariablePreset {
	if in == nil {
		return nil
	}
	out := new(DashboardTemplateVariablePreset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardTemplateVariablePresetValue) DeepCopyInto(out *DashboardTemplateVariablePresetValue) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardTemplateVariablePresetValue.
func (in *DashboardTemplateVariablePresetValue) DeepCopy() *DashboardTemplateVariablePresetValue {
	if in == nil {
		return nil
	}
	out := new(DashboardTemplateVariablePresetValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogAgentProfile) DeepCopyInto(out *DatadogAgentProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogAgentProfile.
func (in *DatadogAgentProfile) DeepCopy() *DatadogAgentProfile {
	if in == nil {
		return nil
	}
	out := new(DatadogAgentProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatadogAgentProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogAgentProfileList) DeepCopyInto(out *DatadogAgentProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatadogAgentProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogAgentProfileList.
func (in *DatadogAgentProfileList) DeepCopy() *DatadogAgentProfileList {
	if in == nil {
		return nil
	}
	out := new(DatadogAgentProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatadogAgentProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogAgentProfileSpec) DeepCopyInto(out *DatadogAgentProfileSpec) {
	*out = *in
	if in.ProfileAffinity != nil {
		in, out := &in.ProfileAffinity, &out.ProfileAffinity
		*out = new(ProfileAffinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(Config)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogAgentProfileSpec.
func (in *DatadogAgentProfileSpec) DeepCopy() *DatadogAgentProfileSpec {
	if in == nil {
		return nil
	}
	out := new(DatadogAgentProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogAgentProfileStatus) DeepCopyInto(out *DatadogAgentProfileStatus) {
	*out = *in
	if in.LastUpdate != nil {
		in, out := &in.LastUpdate, &out.LastUpdate
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogAgentProfileStatus.
func (in *DatadogAgentProfileStatus) DeepCopy() *DatadogAgentProfileStatus {
	if in == nil {
		return nil
	}
	out := new(DatadogAgentProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogDashboard) DeepCopyInto(out *DatadogDashboard) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogDashboard.
func (in *DatadogDashboard) DeepCopy() *DatadogDashboard {
	if in == nil {
		return nil
	}
	out := new(DatadogDashboard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatadogDashboard) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogDashboardList) DeepCopyInto(out *DatadogDashboardList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatadogDashboard, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogDashboardList.
func (in *DatadogDashboardList) DeepCopy() *DatadogDashboardList {
	if in == nil {
		return nil
	}
	out := new(DatadogDashboardList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatadogDashboardList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogDashboardSpec) DeepCopyInto(out *DatadogDashboardSpec) {
	*out = *in
	if in.NotifyList != nil {
		in, out := &in.NotifyList, &out.NotifyList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ReflowType != nil {
		in, out := &in.ReflowType, &out.ReflowType
		*out = new(datadogV1.DashboardReflowType)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TemplateVariablePresets != nil {
		in, out := &in.TemplateVariablePresets, &out.TemplateVariablePresets
		*out = make([]DashboardTemplateVariablePreset, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TemplateVariables != nil {
		in, out := &in.TemplateVariables, &out.TemplateVariables
		*out = make([]DashboardTemplateVariable, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Widgets != nil {
		in, out := &in.Widgets, &out.Widgets
		*out = make([]Widget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogDashboardSpec.
func (in *DatadogDashboardSpec) DeepCopy() *DatadogDashboardSpec {
	if in == nil {
		return nil
	}
	out := new(DatadogDashboardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogDashboardStatus) DeepCopyInto(out *DatadogDashboardStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Created != nil {
		in, out := &in.Created, &out.Created
		*out = (*in).DeepCopy()
	}
	if in.LastForceSyncTime != nil {
		in, out := &in.LastForceSyncTime, &out.LastForceSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogDashboardStatus.
func (in *DatadogDashboardStatus) DeepCopy() *DatadogDashboardStatus {
	if in == nil {
		return nil
	}
	out := new(DatadogDashboardStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogMetric) DeepCopyInto(out *DatadogMetric) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogMetric.
func (in *DatadogMetric) DeepCopy() *DatadogMetric {
	if in == nil {
		return nil
	}
	out := new(DatadogMetric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatadogMetric) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogMetricCondition) DeepCopyInto(out *DatadogMetricCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogMetricCondition.
func (in *DatadogMetricCondition) DeepCopy() *DatadogMetricCondition {
	if in == nil {
		return nil
	}
	out := new(DatadogMetricCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogMetricList) DeepCopyInto(out *DatadogMetricList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatadogMetric, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogMetricList.
func (in *DatadogMetricList) DeepCopy() *DatadogMetricList {
	if in == nil {
		return nil
	}
	out := new(DatadogMetricList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatadogMetricList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogMetricSpec) DeepCopyInto(out *DatadogMetricSpec) {
	*out = *in
	out.MaxAge = in.MaxAge
	out.TimeWindow = in.TimeWindow
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogMetricSpec.
func (in *DatadogMetricSpec) DeepCopy() *DatadogMetricSpec {
	if in == nil {
		return nil
	}
	out := new(DatadogMetricSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogMetricStatus) DeepCopyInto(out *DatadogMetricStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]DatadogMetricCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogMetricStatus.
func (in *DatadogMetricStatus) DeepCopy() *DatadogMetricStatus {
	if in == nil {
		return nil
	}
	out := new(DatadogMetricStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogMonitor) DeepCopyInto(out *DatadogMonitor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogMonitor.
func (in *DatadogMonitor) DeepCopy() *DatadogMonitor {
	if in == nil {
		return nil
	}
	out := new(DatadogMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatadogMonitor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogMonitorCondition) DeepCopyInto(out *DatadogMonitorCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogMonitorCondition.
func (in *DatadogMonitorCondition) DeepCopy() *DatadogMonitorCondition {
	if in == nil {
		return nil
	}
	out := new(DatadogMonitorCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogMonitorControllerOptions) DeepCopyInto(out *DatadogMonitorControllerOptions) {
	*out = *in
	if in.DisableRequiredTags != nil {
		in, out := &in.DisableRequiredTags, &out.DisableRequiredTags
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogMonitorControllerOptions.
func (in *DatadogMonitorControllerOptions) DeepCopy() *DatadogMonitorControllerOptions {
	if in == nil {
		return nil
	}
	out := new(DatadogMonitorControllerOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogMonitorDowntimeStatus) DeepCopyInto(out *DatadogMonitorDowntimeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogMonitorDowntimeStatus.
func (in *DatadogMonitorDowntimeStatus) DeepCopy() *DatadogMonitorDowntimeStatus {
	if in == nil {
		return nil
	}
	out := new(DatadogMonitorDowntimeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogMonitorList) DeepCopyInto(out *DatadogMonitorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatadogMonitor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogMonitorList.
func (in *DatadogMonitorList) DeepCopy() *DatadogMonitorList {
	if in == nil {
		return nil
	}
	out := new(DatadogMonitorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatadogMonitorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogMonitorOptions) DeepCopyInto(out *DatadogMonitorOptions) {
	*out = *in
	if in.EnableLogsSample != nil {
		in, out := &in.EnableLogsSample, &out.EnableLogsSample
		*out = new(bool)
		**out = **in
	}
	if in.EscalationMessage != nil {
		in, out := &in.EscalationMessage, &out.EscalationMessage
		*out = new(string)
		**out = **in
	}
	if in.EvaluationDelay != nil {
		in, out := &in.EvaluationDelay, &out.EvaluationDelay
		*out = new(int64)
		**out = **in
	}
	if in.IncludeTags != nil {
		in, out := &in.IncludeTags, &out.IncludeTags
		*out = new(bool)
		**out = **in
	}
	if in.GroupbySimpleMonitor != nil {
		in, out := &in.GroupbySimpleMonitor, &out.GroupbySimpleMonitor
		*out = new(bool)
		**out = **in
	}
	if in.Locked != nil {
		in, out := &in.Locked, &out.Locked
		*out = new(bool)
		**out = **in
	}
	if in.NewGroupDelay != nil {
		in, out := &in.NewGroupDelay, &out.NewGroupDelay
		*out = new(int64)
		**out = **in
	}
	if in.NoDataTimeframe != nil {
		in, out := &in.NoDataTimeframe, &out.NoDataTimeframe
		*out = new(int64)
		**out = **in
	}
	if in.NotifyAudit != nil {
		in, out := &in.NotifyAudit, &out.NotifyAudit
		*out = new(bool)
		**out = **in
	}
	if in.NotifyBy != nil {
		in, out := &in.NotifyBy, &out.NotifyBy
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NotifyNoData != nil {
		in, out := &in.NotifyNoData, &out.NotifyNoData
		*out = new(bool)
		**out = **in
	}
	if in.RenotifyInterval != nil {
		in, out := &in.RenotifyInterval, &out.RenotifyInterval
		*out = new(int64)
		**out = **in
	}
	if in.RenotifyOccurrences != nil {
		in, out := &in.RenotifyOccurrences, &out.RenotifyOccurrences
		*out = new(int64)
		**out = **in
	}
	if in.RenotifyStatuses != nil {
		in, out := &in.RenotifyStatuses, &out.RenotifyStatuses
		*out = make([]datadogV1.MonitorRenotifyStatusType, len(*in))
		copy(*out, *in)
	}
	if in.RequireFullWindow != nil {
		in, out := &in.RequireFullWindow, &out.RequireFullWindow
		*out = new(bool)
		**out = **in
	}
	if in.TimeoutH != nil {
		in, out := &in.TimeoutH, &out.TimeoutH
		*out = new(int64)
		**out = **in
	}
	if in.Thresholds != nil {
		in, out := &in.Thresholds, &out.Thresholds
		*out = new(DatadogMonitorOptionsThresholds)
		(*in).DeepCopyInto(*out)
	}
	if in.ThresholdWindows != nil {
		in, out := &in.ThresholdWindows, &out.ThresholdWindows
		*out = new(DatadogMonitorOptionsThresholdWindows)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogMonitorOptions.
func (in *DatadogMonitorOptions) DeepCopy() *DatadogMonitorOptions {
	if in == nil {
		return nil
	}
	out := new(DatadogMonitorOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogMonitorOptionsThresholdWindows) DeepCopyInto(out *DatadogMonitorOptionsThresholdWindows) {
	*out = *in
	if in.RecoveryWindow != nil {
		in, out := &in.RecoveryWindow, &out.RecoveryWindow
		*out = new(string)
		**out = **in
	}
	if in.TriggerWindow != nil {
		in, out := &in.TriggerWindow, &out.TriggerWindow
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogMonitorOptionsThresholdWindows.
func (in *DatadogMonitorOptionsThresholdWindows) DeepCopy() *DatadogMonitorOptionsThresholdWindows {
	if in == nil {
		return nil
	}
	out := new(DatadogMonitorOptionsThresholdWindows)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogMonitorOptionsThresholds) DeepCopyInto(out *DatadogMonitorOptionsThresholds) {
	*out = *in
	if in.Critical != nil {
		in, out := &in.Critical, &out.Critical
		*out = new(string)
		**out = **in
	}
	if in.CriticalRecovery != nil {
		in, out := &in.CriticalRecovery, &out.CriticalRecovery
		*out = new(string)
		**out = **in
	}
	if in.OK != nil {
		in, out := &in.OK, &out.OK
		*out = new(string)
		**out = **in
	}
	if in.Unknown != nil {
		in, out := &in.Unknown, &out.Unknown
		*out = new(string)
		**out = **in
	}
	if in.Warning != nil {
		in, out := &in.Warning, &out.Warning
		*out = new(string)
		**out = **in
	}
	if in.WarningRecovery != nil {
		in, out := &in.WarningRecovery, &out.WarningRecovery
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogMonitorOptionsThresholds.
func (in *DatadogMonitorOptionsThresholds) DeepCopy() *DatadogMonitorOptionsThresholds {
	if in == nil {
		return nil
	}
	out := new(DatadogMonitorOptionsThresholds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogMonitorSpec) DeepCopyInto(out *DatadogMonitorSpec) {
	*out = *in
	if in.RestrictedRoles != nil {
		in, out := &in.RestrictedRoles, &out.RestrictedRoles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Options.DeepCopyInto(&out.Options)
	in.ControllerOptions.DeepCopyInto(&out.ControllerOptions)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogMonitorSpec.
func (in *DatadogMonitorSpec) DeepCopy() *DatadogMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(DatadogMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogMonitorStatus) DeepCopyInto(out *DatadogMonitorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]DatadogMonitorCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Created != nil {
		in, out := &in.Created, &out.Created
		*out = (*in).DeepCopy()
	}
	if in.MonitorLastForceSyncTime != nil {
		in, out := &in.MonitorLastForceSyncTime, &out.MonitorLastForceSyncTime
		*out = (*in).DeepCopy()
	}
	if in.MonitorStateLastUpdateTime != nil {
		in, out := &in.MonitorStateLastUpdateTime, &out.MonitorStateLastUpdateTime
		*out = (*in).DeepCopy()
	}
	if in.MonitorStateLastTransitionTime != nil {
		in, out := &in.MonitorStateLastTransitionTime, &out.MonitorStateLastTransitionTime
		*out = (*in).DeepCopy()
	}
	if in.TriggeredState != nil {
		in, out := &in.TriggeredState, &out.TriggeredState
		*out = make([]DatadogMonitorTriggeredState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.DowntimeStatus = in.DowntimeStatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogMonitorStatus.
func (in *DatadogMonitorStatus) DeepCopy() *DatadogMonitorStatus {
	if in == nil {
		return nil
	}
	out := new(DatadogMonitorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogMonitorTriggeredState) DeepCopyInto(out *DatadogMonitorTriggeredState) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogMonitorTriggeredState.
func (in *DatadogMonitorTriggeredState) DeepCopy() *DatadogMonitorTriggeredState {
	if in == nil {
		return nil
	}
	out := new(DatadogMonitorTriggeredState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscaler) DeepCopyInto(out *DatadogPodAutoscaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscaler.
func (in *DatadogPodAutoscaler) DeepCopy() *DatadogPodAutoscaler {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatadogPodAutoscaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerCondition) DeepCopyInto(out *DatadogPodAutoscalerCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerCondition.
func (in *DatadogPodAutoscalerCondition) DeepCopy() *DatadogPodAutoscalerCondition {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerConstraints) DeepCopyInto(out *DatadogPodAutoscalerConstraints) {
	*out = *in
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]DatadogPodAutoscalerContainerConstraints, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerConstraints.
func (in *DatadogPodAutoscalerConstraints) DeepCopy() *DatadogPodAutoscalerConstraints {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerConstraints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerContainerConstraints) DeepCopyInto(out *DatadogPodAutoscalerContainerConstraints) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = new(DatadogPodAutoscalerContainerResourceConstraints)
		(*in).DeepCopyInto(*out)
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(DatadogPodAutoscalerContainerResourceConstraints)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerContainerConstraints.
func (in *DatadogPodAutoscalerContainerConstraints) DeepCopy() *DatadogPodAutoscalerContainerConstraints {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerContainerConstraints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerContainerResourceConstraints) DeepCopyInto(out *DatadogPodAutoscalerContainerResourceConstraints) {
	*out = *in
	if in.MinAllowed != nil {
		in, out := &in.MinAllowed, &out.MinAllowed
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.MaxAllowed != nil {
		in, out := &in.MaxAllowed, &out.MaxAllowed
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerContainerResourceConstraints.
func (in *DatadogPodAutoscalerContainerResourceConstraints) DeepCopy() *DatadogPodAutoscalerContainerResourceConstraints {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerContainerResourceConstraints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerContainerResourceTarget) DeepCopyInto(out *DatadogPodAutoscalerContainerResourceTarget) {
	*out = *in
	in.Value.DeepCopyInto(&out.Value)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerContainerResourceTarget.
func (in *DatadogPodAutoscalerContainerResourceTarget) DeepCopy() *DatadogPodAutoscalerContainerResourceTarget {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerContainerResourceTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerContainerResources) DeepCopyInto(out *DatadogPodAutoscalerContainerResources) {
	*out = *in
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerContainerResources.
func (in *DatadogPodAutoscalerContainerResources) DeepCopy() *DatadogPodAutoscalerContainerResources {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerContainerResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerHorizontalAction) DeepCopyInto(out *DatadogPodAutoscalerHorizontalAction) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
	if in.RecommendedReplicas != nil {
		in, out := &in.RecommendedReplicas, &out.RecommendedReplicas
		*out = new(int32)
		**out = **in
	}
	if in.LimitedReason != nil {
		in, out := &in.LimitedReason, &out.LimitedReason
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerHorizontalAction.
func (in *DatadogPodAutoscalerHorizontalAction) DeepCopy() *DatadogPodAutoscalerHorizontalAction {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerHorizontalAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerHorizontalStatus) DeepCopyInto(out *DatadogPodAutoscalerHorizontalStatus) {
	*out = *in
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(DatadogPodAutoscalerHorizontalTargetStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.LastActions != nil {
		in, out := &in.LastActions, &out.LastActions
		*out = make([]DatadogPodAutoscalerHorizontalAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerHorizontalStatus.
func (in *DatadogPodAutoscalerHorizontalStatus) DeepCopy() *DatadogPodAutoscalerHorizontalStatus {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerHorizontalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerHorizontalTargetStatus) DeepCopyInto(out *DatadogPodAutoscalerHorizontalTargetStatus) {
	*out = *in
	in.GeneratedAt.DeepCopyInto(&out.GeneratedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerHorizontalTargetStatus.
func (in *DatadogPodAutoscalerHorizontalTargetStatus) DeepCopy() *DatadogPodAutoscalerHorizontalTargetStatus {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerHorizontalTargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerList) DeepCopyInto(out *DatadogPodAutoscalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatadogPodAutoscaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerList.
func (in *DatadogPodAutoscalerList) DeepCopy() *DatadogPodAutoscalerList {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatadogPodAutoscalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerPolicy) DeepCopyInto(out *DatadogPodAutoscalerPolicy) {
	*out = *in
	if in.Update != nil {
		in, out := &in.Update, &out.Update
		*out = new(DatadogPodAutoscalerUpdatePolicy)
		**out = **in
	}
	if in.Upscale != nil {
		in, out := &in.Upscale, &out.Upscale
		*out = new(DatadogPodAutoscalerScalingPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Downscale != nil {
		in, out := &in.Downscale, &out.Downscale
		*out = new(DatadogPodAutoscalerScalingPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerPolicy.
func (in *DatadogPodAutoscalerPolicy) DeepCopy() *DatadogPodAutoscalerPolicy {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerResourceTarget) DeepCopyInto(out *DatadogPodAutoscalerResourceTarget) {
	*out = *in
	in.Value.DeepCopyInto(&out.Value)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerResourceTarget.
func (in *DatadogPodAutoscalerResourceTarget) DeepCopy() *DatadogPodAutoscalerResourceTarget {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerResourceTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerScalingPolicy) DeepCopyInto(out *DatadogPodAutoscalerScalingPolicy) {
	*out = *in
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(DatadogPodAutoscalerScalingStrategySelect)
		**out = **in
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]DatadogPodAutoscalerScalingRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerScalingPolicy.
func (in *DatadogPodAutoscalerScalingPolicy) DeepCopy() *DatadogPodAutoscalerScalingPolicy {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerScalingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerScalingRule) DeepCopyInto(out *DatadogPodAutoscalerScalingRule) {
	*out = *in
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = new(DatadogPodAutoscalerScalingRuleMatch)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerScalingRule.
func (in *DatadogPodAutoscalerScalingRule) DeepCopy() *DatadogPodAutoscalerScalingRule {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerScalingRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerSpec) DeepCopyInto(out *DatadogPodAutoscalerSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	if in.RemoteVersion != nil {
		in, out := &in.RemoteVersion, &out.RemoteVersion
		*out = new(uint64)
		**out = **in
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(DatadogPodAutoscalerPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]DatadogPodAutoscalerTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Constraints != nil {
		in, out := &in.Constraints, &out.Constraints
		*out = new(DatadogPodAutoscalerConstraints)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerSpec.
func (in *DatadogPodAutoscalerSpec) DeepCopy() *DatadogPodAutoscalerSpec {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerStatus) DeepCopyInto(out *DatadogPodAutoscalerStatus) {
	*out = *in
	if in.Vertical != nil {
		in, out := &in.Vertical, &out.Vertical
		*out = new(DatadogPodAutoscalerVerticalStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Horizontal != nil {
		in, out := &in.Horizontal, &out.Horizontal
		*out = new(DatadogPodAutoscalerHorizontalStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.CurrentReplicas != nil {
		in, out := &in.CurrentReplicas, &out.CurrentReplicas
		*out = new(int32)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]DatadogPodAutoscalerCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerStatus.
func (in *DatadogPodAutoscalerStatus) DeepCopy() *DatadogPodAutoscalerStatus {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerTarget) DeepCopyInto(out *DatadogPodAutoscalerTarget) {
	*out = *in
	if in.PodResource != nil {
		in, out := &in.PodResource, &out.PodResource
		*out = new(DatadogPodAutoscalerResourceTarget)
		(*in).DeepCopyInto(*out)
	}
	if in.ContainerResource != nil {
		in, out := &in.ContainerResource, &out.ContainerResource
		*out = new(DatadogPodAutoscalerContainerResourceTarget)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerTarget.
func (in *DatadogPodAutoscalerTarget) DeepCopy() *DatadogPodAutoscalerTarget {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerTargetValue) DeepCopyInto(out *DatadogPodAutoscalerTargetValue) {
	*out = *in
	if in.Absolute != nil {
		in, out := &in.Absolute, &out.Absolute
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Utilization != nil {
		in, out := &in.Utilization, &out.Utilization
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerTargetValue.
func (in *DatadogPodAutoscalerTargetValue) DeepCopy() *DatadogPodAutoscalerTargetValue {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerTargetValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerUpdatePolicy) DeepCopyInto(out *DatadogPodAutoscalerUpdatePolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerUpdatePolicy.
func (in *DatadogPodAutoscalerUpdatePolicy) DeepCopy() *DatadogPodAutoscalerUpdatePolicy {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerUpdatePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerVerticalAction) DeepCopyInto(out *DatadogPodAutoscalerVerticalAction) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerVerticalAction.
func (in *DatadogPodAutoscalerVerticalAction) DeepCopy() *DatadogPodAutoscalerVerticalAction {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerVerticalAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerVerticalStatus) DeepCopyInto(out *DatadogPodAutoscalerVerticalStatus) {
	*out = *in
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(DatadogPodAutoscalerVerticalTargetStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.LastAction != nil {
		in, out := &in.LastAction, &out.LastAction
		*out = new(DatadogPodAutoscalerVerticalAction)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerVerticalStatus.
func (in *DatadogPodAutoscalerVerticalStatus) DeepCopy() *DatadogPodAutoscalerVerticalStatus {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerVerticalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerVerticalTargetStatus) DeepCopyInto(out *DatadogPodAutoscalerVerticalTargetStatus) {
	*out = *in
	in.GeneratedAt.DeepCopyInto(&out.GeneratedAt)
	if in.Scaled != nil {
		in, out := &in.Scaled, &out.Scaled
		*out = new(int32)
		**out = **in
	}
	if in.DesiredResources != nil {
		in, out := &in.DesiredResources, &out.DesiredResources
		*out = make([]DatadogPodAutoscalerContainerResources, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.PODCPURequest = in.PODCPURequest.DeepCopy()
	out.PODMemoryRequest = in.PODMemoryRequest.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerVerticalTargetStatus.
func (in *DatadogPodAutoscalerVerticalTargetStatus) DeepCopy() *DatadogPodAutoscalerVerticalTargetStatus {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerVerticalTargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogSLO) DeepCopyInto(out *DatadogSLO) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogSLO.
func (in *DatadogSLO) DeepCopy() *DatadogSLO {
	if in == nil {
		return nil
	}
	out := new(DatadogSLO)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatadogSLO) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogSLOControllerOptions) DeepCopyInto(out *DatadogSLOControllerOptions) {
	*out = *in
	if in.DisableRequiredTags != nil {
		in, out := &in.DisableRequiredTags, &out.DisableRequiredTags
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogSLOControllerOptions.
func (in *DatadogSLOControllerOptions) DeepCopy() *DatadogSLOControllerOptions {
	if in == nil {
		return nil
	}
	out := new(DatadogSLOControllerOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogSLOList) DeepCopyInto(out *DatadogSLOList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatadogSLO, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogSLOList.
func (in *DatadogSLOList) DeepCopy() *DatadogSLOList {
	if in == nil {
		return nil
	}
	out := new(DatadogSLOList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatadogSLOList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogSLOQuery) DeepCopyInto(out *DatadogSLOQuery) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogSLOQuery.
func (in *DatadogSLOQuery) DeepCopy() *DatadogSLOQuery {
	if in == nil {
		return nil
	}
	out := new(DatadogSLOQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogSLOSpec) DeepCopyInto(out *DatadogSLOSpec) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MonitorIDs != nil {
		in, out := &in.MonitorIDs, &out.MonitorIDs
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Query != nil {
		in, out := &in.Query, &out.Query
		*out = new(DatadogSLOQuery)
		**out = **in
	}
	out.TargetThreshold = in.TargetThreshold.DeepCopy()
	if in.WarningThreshold != nil {
		in, out := &in.WarningThreshold, &out.WarningThreshold
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.ControllerOptions != nil {
		in, out := &in.ControllerOptions, &out.ControllerOptions
		*out = new(DatadogSLOControllerOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogSLOSpec.
func (in *DatadogSLOSpec) DeepCopy() *DatadogSLOSpec {
	if in == nil {
		return nil
	}
	out := new(DatadogSLOSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogSLOStatus) DeepCopyInto(out *DatadogSLOStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Created != nil {
		in, out := &in.Created, &out.Created
		*out = (*in).DeepCopy()
	}
	if in.LastForceSyncTime != nil {
		in, out := &in.LastForceSyncTime, &out.LastForceSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogSLOStatus.
func (in *DatadogSLOStatus) DeepCopy() *DatadogSLOStatus {
	if in == nil {
		return nil
	}
	out := new(DatadogSLOStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FormulaAndFunctionApmDependencyStatsQueryDefinition) DeepCopyInto(out *FormulaAndFunctionApmDependencyStatsQueryDefinition) {
	*out = *in
	if in.CrossOrgUuids != nil {
		in, out := &in.CrossOrgUuids, &out.CrossOrgUuids
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IsUpstream != nil {
		in, out := &in.IsUpstream, &out.IsUpstream
		*out = new(bool)
		**out = **in
	}
	if in.PrimaryTagName != nil {
		in, out := &in.PrimaryTagName, &out.PrimaryTagName
		*out = new(string)
		**out = **in
	}
	if in.PrimaryTagValue != nil {
		in, out := &in.PrimaryTagValue, &out.PrimaryTagValue
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FormulaAndFunctionApmDependencyStatsQueryDefinition.
func (in *FormulaAndFunctionApmDependencyStatsQueryDefinition) DeepCopy() *FormulaAndFunctionApmDependencyStatsQueryDefinition {
	if in == nil {
		return nil
	}
	out := new(FormulaAndFunctionApmDependencyStatsQueryDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FormulaAndFunctionApmResourceStatsQueryDefinition) DeepCopyInto(out *FormulaAndFunctionApmResourceStatsQueryDefinition) {
	*out = *in
	if in.CrossOrgUuids != nil {
		in, out := &in.CrossOrgUuids, &out.CrossOrgUuids
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GroupBy != nil {
		in, out := &in.GroupBy, &out.GroupBy
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OperationName != nil {
		in, out := &in.OperationName, &out.OperationName
		*out = new(string)
		**out = **in
	}
	if in.PrimaryTagName != nil {
		in, out := &in.PrimaryTagName, &out.PrimaryTagName
		*out = new(string)
		**out = **in
	}
	if in.PrimaryTagValue != nil {
		in, out := &in.PrimaryTagValue, &out.PrimaryTagValue
		*out = new(string)
		**out = **in
	}
	if in.ResourceName != nil {
		in, out := &in.ResourceName, &out.ResourceName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FormulaAndFunctionApmResourceStatsQueryDefinition.
func (in *FormulaAndFunctionApmResourceStatsQueryDefinition) DeepCopy() *FormulaAndFunctionApmResourceStatsQueryDefinition {
	if in == nil {
		return nil
	}
	out := new(FormulaAndFunctionApmResourceStatsQueryDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FormulaAndFunctionCloudCostQueryDefinition) DeepCopyInto(out *FormulaAndFunctionCloudCostQueryDefinition) {
	*out = *in
	if in.Aggregator != nil {
		in, out := &in.Aggregator, &out.Aggregator
		*out = new(datadogV1.WidgetAggregator)
		**out = **in
	}
	if in.CrossOrgUuids != nil {
		in, out := &in.CrossOrgUuids, &out.CrossOrgUuids
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FormulaAndFunctionCloudCostQueryDefinition.
func (in *FormulaAndFunctionCloudCostQueryDefinition) DeepCopy() *FormulaAndFunctionCloudCostQueryDefinition {
	if in == nil {
		return nil
	}
	out := new(FormulaAndFunctionCloudCostQueryDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FormulaAndFunctionEventQueryDefinition) DeepCopyInto(out *FormulaAndFunctionEventQueryDefinition) {
	*out = *in
	if in.Compute != nil {
		in, out := &in.Compute, &out.Compute
		*out = new(FormulaAndFunctionEventQueryDefinitionCompute)
		(*in).DeepCopyInto(*out)
	}
	if in.CrossOrgUuids != nil {
		in, out := &in.CrossOrgUuids, &out.CrossOrgUuids
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GroupBy != nil {
		in, out := &in.GroupBy, &out.GroupBy
		*out = make([]FormulaAndFunctionEventQueryGroupBy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Indexes != nil {
		in, out := &in.Indexes, &out.Indexes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Search != nil {
		in, out := &in.Search, &out.Search
		*out = new(FormulaAndFunctionEventQueryDefinitionSearch)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FormulaAndFunctionEventQueryDefinition.
func (in *FormulaAndFunctionEventQueryDefinition) DeepCopy() *FormulaAndFunctionEventQueryDefinition {
	if in == nil {
		return nil
	}
	out := new(FormulaAndFunctionEventQueryDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FormulaAndFunctionEventQueryDefinitionCompute) DeepCopyInto(out *FormulaAndFunctionEventQueryDefinitionCompute) {
	*out = *in
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(int64)
		**out = **in
	}
	if in.Metric != nil {
		in, out := &in.Metric, &out.Metric
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FormulaAndFunctionEventQueryDefinitionCompute.
func (in *FormulaAndFunctionEventQueryDefinitionCompute) DeepCopy() *FormulaAndFunctionEventQueryDefinitionCompute {
	if in == nil {
		return nil
	}
	out := new(FormulaAndFunctionEventQueryDefinitionCompute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FormulaAndFunctionEventQueryDefinitionSearch) DeepCopyInto(out *FormulaAndFunctionEventQueryDefinitionSearch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FormulaAndFunctionEventQueryDefinitionSearch.
func (in *FormulaAndFunctionEventQueryDefinitionSearch) DeepCopy() *FormulaAndFunctionEventQueryDefinitionSearch {
	if in == nil {
		return nil
	}
	out := new(FormulaAndFunctionEventQueryDefinitionSearch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FormulaAndFunctionEventQueryGroupBy) DeepCopyInto(out *FormulaAndFunctionEventQueryGroupBy) {
	*out = *in
	if in.Limit != nil {
		in, out := &in.Limit, &out.Limit
		*out = new(int64)
		**out = **in
	}
	if in.Sort != nil {
		in, out := &in.Sort, &out.Sort
		*out = new(FormulaAndFunctionEventQueryGroupBySort)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FormulaAndFunctionEventQueryGroupBy.
func (in *FormulaAndFunctionEventQueryGroupBy) DeepCopy() *FormulaAndFunctionEventQueryGroupBy {
	if in == nil {
		return nil
	}
	out := new(FormulaAndFunctionEventQueryGroupBy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FormulaAndFunctionEventQueryGroupBySort) DeepCopyInto(out *FormulaAndFunctionEventQueryGroupBySort) {
	*out = *in
	if in.Metric != nil {
		in, out := &in.Metric, &out.Metric
		*out = new(string)
		**out = **in
	}
	if in.Order != nil {
		in, out := &in.Order, &out.Order
		*out = new(datadogV1.QuerySortOrder)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FormulaAndFunctionEventQueryGroupBySort.
func (in *FormulaAndFunctionEventQueryGroupBySort) DeepCopy() *FormulaAndFunctionEventQueryGroupBySort {
	if in == nil {
		return nil
	}
	out := new(FormulaAndFunctionEventQueryGroupBySort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FormulaAndFunctionMetricQueryDefinition) DeepCopyInto(out *FormulaAndFunctionMetricQueryDefinition) {
	*out = *in
	if in.Aggregator != nil {
		in, out := &in.Aggregator, &out.Aggregator
		*out = new(datadogV1.FormulaAndFunctionMetricAggregation)
		**out = **in
	}
	if in.CrossOrgUuids != nil {
		in, out := &in.CrossOrgUuids, &out.CrossOrgUuids
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FormulaAndFunctionMetricQueryDefinition.
func (in *FormulaAndFunctionMetricQueryDefinition) DeepCopy() *FormulaAndFunctionMetricQueryDefinition {
	if in == nil {
		return nil
	}
	out := new(FormulaAndFunctionMetricQueryDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FormulaAndFunctionProcessQueryDefinition) DeepCopyInto(out *FormulaAndFunctionProcessQueryDefinition) {
	*out = *in
	if in.Aggregator != nil {
		in, out := &in.Aggregator, &out.Aggregator
		*out = new(datadogV1.FormulaAndFunctionMetricAggregation)
		**out = **in
	}
	if in.CrossOrgUuids != nil {
		in, out := &in.CrossOrgUuids, &out.CrossOrgUuids
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IsNormalizedCpu != nil {
		in, out := &in.IsNormalizedCpu, &out.IsNormalizedCpu
		*out = new(bool)
		**out = **in
	}
	if in.Limit != nil {
		in, out := &in.Limit, &out.Limit
		*out = new(int64)
		**out = **in
	}
	if in.Sort != nil {
		in, out := &in.Sort, &out.Sort
		*out = new(datadogV1.QuerySortOrder)
		**out = **in
	}
	if in.TagFilters != nil {
		in, out := &in.TagFilters, &out.TagFilters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TextFilter != nil {
		in, out := &in.TextFilter, &out.TextFilter
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FormulaAndFunctionProcessQueryDefinition.
func (in *FormulaAndFunctionProcessQueryDefinition) DeepCopy() *FormulaAndFunctionProcessQueryDefinition {
	if in == nil {
		return nil
	}
	out := new(FormulaAndFunctionProcessQueryDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FormulaAndFunctionQueryDefinition) DeepCopyInto(out *FormulaAndFunctionQueryDefinition) {
	*out = *in
	if in.FormulaAndFunctionMetricQueryDefinition != nil {
		in, out := &in.FormulaAndFunctionMetricQueryDefinition, &out.FormulaAndFunctionMetricQueryDefinition
		*out = new(FormulaAndFunctionMetricQueryDefinition)
		(*in).DeepCopyInto(*out)
	}
	if in.FormulaAndFunctionEventQueryDefinition != nil {
		in, out := &in.FormulaAndFunctionEventQueryDefinition, &out.FormulaAndFunctionEventQueryDefinition
		*out = new(FormulaAndFunctionEventQueryDefinition)
		(*in).DeepCopyInto(*out)
	}
	if in.FormulaAndFunctionProcessQueryDefinition != nil {
		in, out := &in.FormulaAndFunctionProcessQueryDefinition, &out.FormulaAndFunctionProcessQueryDefinition
		*out = new(FormulaAndFunctionProcessQueryDefinition)
		(*in).DeepCopyInto(*out)
	}
	if in.FormulaAndFunctionApmDependencyStatsQueryDefinition != nil {
		in, out := &in.FormulaAndFunctionApmDependencyStatsQueryDefinition, &out.FormulaAndFunctionApmDependencyStatsQueryDefinition
		*out = new(FormulaAndFunctionApmDependencyStatsQueryDefinition)
		(*in).DeepCopyInto(*out)
	}
	if in.FormulaAndFunctionApmResourceStatsQueryDefinition != nil {
		in, out := &in.FormulaAndFunctionApmResourceStatsQueryDefinition, &out.FormulaAndFunctionApmResourceStatsQueryDefinition
		*out = new(FormulaAndFunctionApmResourceStatsQueryDefinition)
		(*in).DeepCopyInto(*out)
	}
	if in.FormulaAndFunctionSLOQueryDefinition != nil {
		in, out := &in.FormulaAndFunctionSLOQueryDefinition, &out.FormulaAndFunctionSLOQueryDefinition
		*out = new(FormulaAndFunctionSLOQueryDefinition)
		(*in).DeepCopyInto(*out)
	}
	if in.FormulaAndFunctionCloudCostQueryDefinition != nil {
		in, out := &in.FormulaAndFunctionCloudCostQueryDefinition, &out.FormulaAndFunctionCloudCostQueryDefinition
		*out = new(FormulaAndFunctionCloudCostQueryDefinition)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FormulaAndFunctionQueryDefinition.
func (in *FormulaAndFunctionQueryDefinition) DeepCopy() *FormulaAndFunctionQueryDefinition {
	if in == nil {
		return nil
	}
	out := new(FormulaAndFunctionQueryDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FormulaAndFunctionSLOQueryDefinition) DeepCopyInto(out *FormulaAndFunctionSLOQueryDefinition) {
	*out = *in
	if in.AdditionalQueryFilters != nil {
		in, out := &in.AdditionalQueryFilters, &out.AdditionalQueryFilters
		*out = new(string)
		**out = **in
	}
	if in.CrossOrgUuids != nil {
		in, out := &in.CrossOrgUuids, &out.CrossOrgUuids
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GroupMode != nil {
		in, out := &in.GroupMode, &out.GroupMode
		*out = new(datadogV1.FormulaAndFunctionSLOGroupMode)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.SloQueryType != nil {
		in, out := &in.SloQueryType, &out.SloQueryType
		*out = new(datadogV1.FormulaAndFunctionSLOQueryType)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FormulaAndFunctionSLOQueryDefinition.
func (in *FormulaAndFunctionSLOQueryDefinition) DeepCopy() *FormulaAndFunctionSLOQueryDefinition {
	if in == nil {
		return nil
	}
	out := new(FormulaAndFunctionSLOQueryDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Override) DeepCopyInto(out *Override) {
	*out = *in
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make(map[commonv1.AgentContainerName]*Container, len(*in))
		for key, val := range *in {
			var outVal *Container
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(Container)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	if in.PriorityClassName != nil {
		in, out := &in.PriorityClassName, &out.PriorityClassName
		*out = new(string)
		**out = **in
	}
	if in.UpdateStrategy != nil {
		in, out := &in.UpdateStrategy, &out.UpdateStrategy
		*out = new(commonv1.UpdateStrategy)
		(*in).DeepCopyInto(*out)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Override.
func (in *Override) DeepCopy() *Override {
	if in == nil {
		return nil
	}
	out := new(Override)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileAffinity) DeepCopyInto(out *ProfileAffinity) {
	*out = *in
	if in.ProfileNodeAffinity != nil {
		in, out := &in.ProfileNodeAffinity, &out.ProfileNodeAffinity
		*out = make([]v1.NodeSelectorRequirement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileAffinity.
func (in *ProfileAffinity) DeepCopy() *ProfileAffinity {
	if in == nil {
		return nil
	}
	out := new(ProfileAffinity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryValueWidgetDefinition) DeepCopyInto(out *QueryValueWidgetDefinition) {
	*out = *in
	if in.Autoscale != nil {
		in, out := &in.Autoscale, &out.Autoscale
		*out = new(bool)
		**out = **in
	}
	if in.CustomLinks != nil {
		in, out := &in.CustomLinks, &out.CustomLinks
		*out = make([]WidgetCustomLink, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomUnit != nil {
		in, out := &in.CustomUnit, &out.CustomUnit
		*out = new(string)
		**out = **in
	}
	if in.Precision != nil {
		in, out := &in.Precision, &out.Precision
		*out = new(int64)
		**out = **in
	}
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = make([]QueryValueWidgetRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TextAlign != nil {
		in, out := &in.TextAlign, &out.TextAlign
		*out = new(datadogV1.WidgetTextAlign)
		**out = **in
	}
	if in.Time != nil {
		in, out := &in.Time, &out.Time
		*out = new(WidgetTime)
		(*in).DeepCopyInto(*out)
	}
	if in.TimeseriesBackground != nil {
		in, out := &in.TimeseriesBackground, &out.TimeseriesBackground
		*out = new(TimeseriesBackground)
		(*in).DeepCopyInto(*out)
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
	if in.TitleAlign != nil {
		in, out := &in.TitleAlign, &out.TitleAlign
		*out = new(datadogV1.WidgetTextAlign)
		**out = **in
	}
	if in.TitleSize != nil {
		in, out := &in.TitleSize, &out.TitleSize
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryValueWidgetDefinition.
func (in *QueryValueWidgetDefinition) DeepCopy() *QueryValueWidgetDefinition {
	if in == nil {
		return nil
	}
	out := new(QueryValueWidgetDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryValueWidgetRequest) DeepCopyInto(out *QueryValueWidgetRequest) {
	*out = *in
	if in.Aggregator != nil {
		in, out := &in.Aggregator, &out.Aggregator
		*out = new(datadogV1.WidgetAggregator)
		**out = **in
	}
	if in.ConditionalFormats != nil {
		in, out := &in.ConditionalFormats, &out.ConditionalFormats
		*out = make([]WidgetConditionalFormat, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Formulas != nil {
		in, out := &in.Formulas, &out.Formulas
		*out = make([]WidgetFormula, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Queries != nil {
		in, out := &in.Queries, &out.Queries
		*out = make([]FormulaAndFunctionQueryDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResponseFormat != nil {
		in, out := &in.ResponseFormat, &out.ResponseFormat
		*out = new(datadogV1.FormulaAndFunctionResponseFormat)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryValueWidgetRequest.
func (in *QueryValueWidgetRequest) DeepCopy() *QueryValueWidgetRequest {
	if in == nil {
		return nil
	}
	out := new(QueryValueWidgetRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeseriesBackground) DeepCopyInto(out *TimeseriesBackground) {
	*out = *in
	if in.Yaxis != nil {
		in, out := &in.Yaxis, &out.Yaxis
		*out = new(WidgetAxis)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeseriesBackground.
func (in *TimeseriesBackground) DeepCopy() *TimeseriesBackground {
	if in == nil {
		return nil
	}
	out := new(TimeseriesBackground)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeseriesWidgetDefinition) DeepCopyInto(out *TimeseriesWidgetDefinition) {
	*out = *in
	if in.CustomLinks != nil {
		in, out := &in.CustomLinks, &out.CustomLinks
		*out = make([]WidgetCustomLink, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = make([]WidgetEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LegendColumns != nil {
		in, out := &in.LegendColumns, &out.LegendColumns
		*out = make([]datadogV1.TimeseriesWidgetLegendColumn, len(*in))
		copy(*out, *in)
	}
	if in.LegendLayout != nil {
		in, out := &in.LegendLayout, &out.LegendLayout
		*out = new(datadogV1.TimeseriesWidgetLegendLayout)
		**out = **in
	}
	if in.LegendSize != nil {
		in, out := &in.LegendSize, &out.LegendSize
		*out = new(string)
		**out = **in
	}
	if in.Markers != nil {
		in, out := &in.Markers, &out.Markers
		*out = make([]WidgetMarker, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = make([]TimeseriesWidgetRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RightYaxis != nil {
		in, out := &in.RightYaxis, &out.RightYaxis
		*out = new(WidgetAxis)
		(*in).DeepCopyInto(*out)
	}
	if in.ShowLegend != nil {
		in, out := &in.ShowLegend, &out.ShowLegend
		*out = new(bool)
		**out = **in
	}
	if in.Time != nil {
		in, out := &in.Time, &out.Time
		*out = new(WidgetTime)
		(*in).DeepCopyInto(*out)
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
	if in.TitleAlign != nil {
		in, out := &in.TitleAlign, &out.TitleAlign
		*out = new(datadogV1.WidgetTextAlign)
		**out = **in
	}
	if in.TitleSize != nil {
		in, out := &in.TitleSize, &out.TitleSize
		*out = new(string)
		**out = **in
	}
	if in.Yaxis != nil {
		in, out := &in.Yaxis, &out.Yaxis
		*out = new(WidgetAxis)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeseriesWidgetDefinition.
func (in *TimeseriesWidgetDefinition) DeepCopy() *TimeseriesWidgetDefinition {
	if in == nil {
		return nil
	}
	out := new(TimeseriesWidgetDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeseriesWidgetExpressionAlias) DeepCopyInto(out *TimeseriesWidgetExpressionAlias) {
	*out = *in
	if in.AliasName != nil {
		in, out := &in.AliasName, &out.AliasName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeseriesWidgetExpressionAlias.
func (in *TimeseriesWidgetExpressionAlias) DeepCopy() *TimeseriesWidgetExpressionAlias {
	if in == nil {
		return nil
	}
	out := new(TimeseriesWidgetExpressionAlias)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeseriesWidgetRequest) DeepCopyInto(out *TimeseriesWidgetRequest) {
	*out = *in
	if in.DisplayType != nil {
		in, out := &in.DisplayType, &out.DisplayType
		*out = new(datadogV1.WidgetDisplayType)
		**out = **in
	}
	if in.Formulas != nil {
		in, out := &in.Formulas, &out.Formulas
		*out = make([]WidgetFormula, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make([]TimeseriesWidgetExpressionAlias, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OnRightYaxis != nil {
		in, out := &in.OnRightYaxis, &out.OnRightYaxis
		*out = new(bool)
		**out = **in
	}
	if in.Queries != nil {
		in, out := &in.Queries, &out.Queries
		*out = make([]FormulaAndFunctionQueryDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResponseFormat != nil {
		in, out := &in.ResponseFormat, &out.ResponseFormat
		*out = new(datadogV1.FormulaAndFunctionResponseFormat)
		**out = **in
	}
	if in.Style != nil {
		in, out := &in.Style, &out.Style
		*out = new(WidgetRequestStyle)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeseriesWidgetRequest.
func (in *TimeseriesWidgetRequest) DeepCopy() *TimeseriesWidgetRequest {
	if in == nil {
		return nil
	}
	out := new(TimeseriesWidgetRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Widget) DeepCopyInto(out *Widget) {
	*out = *in
	if in.TimeseriesWidgetDefinition != nil {
		in, out := &in.TimeseriesWidgetDefinition, &out.TimeseriesWidgetDefinition
		*out = new(TimeseriesWidgetDefinition)
		(*in).DeepCopyInto(*out)
	}
	if in.QueryValueWidgetDefinition != nil {
		in, out := &in.QueryValueWidgetDefinition, &out.QueryValueWidgetDefinition
		*out = new(QueryValueWidgetDefinition)
		(*in).DeepCopyInto(*out)
	}
	if in.Id != nil {
		in, out := &in.Id, &out.Id
		*out = new(int64)
		**out = **in
	}
	in.Layout.DeepCopyInto(&out.Layout)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Widget.
func (in *Widget) DeepCopy() *Widget {
	if in == nil {
		return nil
	}
	out := new(Widget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WidgetAxis) DeepCopyInto(out *WidgetAxis) {
	*out = *in
	if in.IncludeZero != nil {
		in, out := &in.IncludeZero, &out.IncludeZero
		*out = new(bool)
		**out = **in
	}
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(string)
		**out = **in
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(string)
		**out = **in
	}
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(string)
		**out = **in
	}
	if in.Scale != nil {
		in, out := &in.Scale, &out.Scale
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WidgetAxis.
func (in *WidgetAxis) DeepCopy() *WidgetAxis {
	if in == nil {
		return nil
	}
	out := new(WidgetAxis)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WidgetConditionalFormat) DeepCopyInto(out *WidgetConditionalFormat) {
	*out = *in
	if in.CustomBgColor != nil {
		in, out := &in.CustomBgColor, &out.CustomBgColor
		*out = new(string)
		**out = **in
	}
	if in.CustomFgColor != nil {
		in, out := &in.CustomFgColor, &out.CustomFgColor
		*out = new(string)
		**out = **in
	}
	if in.HideValue != nil {
		in, out := &in.HideValue, &out.HideValue
		*out = new(bool)
		**out = **in
	}
	if in.ImageUrl != nil {
		in, out := &in.ImageUrl, &out.ImageUrl
		*out = new(string)
		**out = **in
	}
	if in.Metric != nil {
		in, out := &in.Metric, &out.Metric
		*out = new(string)
		**out = **in
	}
	if in.Timeframe != nil {
		in, out := &in.Timeframe, &out.Timeframe
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WidgetConditionalFormat.
func (in *WidgetConditionalFormat) DeepCopy() *WidgetConditionalFormat {
	if in == nil {
		return nil
	}
	out := new(WidgetConditionalFormat)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WidgetCustomLink) DeepCopyInto(out *WidgetCustomLink) {
	*out = *in
	if in.IsHidden != nil {
		in, out := &in.IsHidden, &out.IsHidden
		*out = new(bool)
		**out = **in
	}
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(string)
		**out = **in
	}
	if in.Link != nil {
		in, out := &in.Link, &out.Link
		*out = new(string)
		**out = **in
	}
	if in.OverrideLabel != nil {
		in, out := &in.OverrideLabel, &out.OverrideLabel
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WidgetCustomLink.
func (in *WidgetCustomLink) DeepCopy() *WidgetCustomLink {
	if in == nil {
		return nil
	}
	out := new(WidgetCustomLink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WidgetEvent) DeepCopyInto(out *WidgetEvent) {
	*out = *in
	if in.TagsExecution != nil {
		in, out := &in.TagsExecution, &out.TagsExecution
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WidgetEvent.
func (in *WidgetEvent) DeepCopy() *WidgetEvent {
	if in == nil {
		return nil
	}
	out := new(WidgetEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WidgetFormula) DeepCopyInto(out *WidgetFormula) {
	*out = *in
	if in.Alias != nil {
		in, out := &in.Alias, &out.Alias
		*out = new(string)
		**out = **in
	}
	if in.CellDisplayMode != nil {
		in, out := &in.CellDisplayMode, &out.CellDisplayMode
		*out = new(datadogV1.TableWidgetCellDisplayMode)
		**out = **in
	}
	if in.ConditionalFormats != nil {
		in, out := &in.ConditionalFormats, &out.ConditionalFormats
		*out = make([]WidgetConditionalFormat, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Limit != nil {
		in, out := &in.Limit, &out.Limit
		*out = new(WidgetFormulaLimit)
		(*in).DeepCopyInto(*out)
	}
	if in.Style != nil {
		in, out := &in.Style, &out.Style
		*out = new(WidgetFormulaStyle)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WidgetFormula.
func (in *WidgetFormula) DeepCopy() *WidgetFormula {
	if in == nil {
		return nil
	}
	out := new(WidgetFormula)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WidgetFormulaLimit) DeepCopyInto(out *WidgetFormulaLimit) {
	*out = *in
	if in.Count != nil {
		in, out := &in.Count, &out.Count
		*out = new(int64)
		**out = **in
	}
	if in.Order != nil {
		in, out := &in.Order, &out.Order
		*out = new(datadogV1.QuerySortOrder)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WidgetFormulaLimit.
func (in *WidgetFormulaLimit) DeepCopy() *WidgetFormulaLimit {
	if in == nil {
		return nil
	}
	out := new(WidgetFormulaLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WidgetFormulaStyle) DeepCopyInto(out *WidgetFormulaStyle) {
	*out = *in
	if in.Palette != nil {
		in, out := &in.Palette, &out.Palette
		*out = new(string)
		**out = **in
	}
	if in.PaletteIndex != nil {
		in, out := &in.PaletteIndex, &out.PaletteIndex
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WidgetFormulaStyle.
func (in *WidgetFormulaStyle) DeepCopy() *WidgetFormulaStyle {
	if in == nil {
		return nil
	}
	out := new(WidgetFormulaStyle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WidgetLayout) DeepCopyInto(out *WidgetLayout) {
	*out = *in
	if in.IsColumnBreak != nil {
		in, out := &in.IsColumnBreak, &out.IsColumnBreak
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WidgetLayout.
func (in *WidgetLayout) DeepCopy() *WidgetLayout {
	if in == nil {
		return nil
	}
	out := new(WidgetLayout)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WidgetMarker) DeepCopyInto(out *WidgetMarker) {
	*out = *in
	if in.DisplayType != nil {
		in, out := &in.DisplayType, &out.DisplayType
		*out = new(string)
		**out = **in
	}
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(string)
		**out = **in
	}
	if in.Time != nil {
		in, out := &in.Time, &out.Time
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WidgetMarker.
func (in *WidgetMarker) DeepCopy() *WidgetMarker {
	if in == nil {
		return nil
	}
	out := new(WidgetMarker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WidgetRequestStyle) DeepCopyInto(out *WidgetRequestStyle) {
	*out = *in
	if in.LineType != nil {
		in, out := &in.LineType, &out.LineType
		*out = new(datadogV1.WidgetLineType)
		**out = **in
	}
	if in.LineWidth != nil {
		in, out := &in.LineWidth, &out.LineWidth
		*out = new(datadogV1.WidgetLineWidth)
		**out = **in
	}
	if in.Palette != nil {
		in, out := &in.Palette, &out.Palette
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WidgetRequestStyle.
func (in *WidgetRequestStyle) DeepCopy() *WidgetRequestStyle {
	if in == nil {
		return nil
	}
	out := new(WidgetRequestStyle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WidgetTime) DeepCopyInto(out *WidgetTime) {
	*out = *in
	if in.LiveSpan != nil {
		in, out := &in.LiveSpan, &out.LiveSpan
		*out = new(datadogV1.WidgetLiveSpan)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WidgetTime.
func (in *WidgetTime) DeepCopy() *WidgetTime {
	if in == nil {
		return nil
	}
	out := new(WidgetTime)
	in.DeepCopyInto(out)
	return out
}
