apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datadog-operator
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  - roles.rbac.authorization.k8s.io
  - authorization.k8s.io
  resources:
  - 'clusterroles'
  - 'clusterrolebindings'
  verbs:
  - '*'
- apiGroups:
  - datadoghq.com
  resources:
  - datadogagents
  - datadogagents/status
  - datadogagents/finalizers
  verbs:
  - '*'
- apiGroups:
  - admissionregistration.k8s.io
  - ''
  resources:
  - 'mutatingwebhookconfigurations'
  - 'secrets'
  verbs:
  - 'get'
  - 'list'
  - 'watch'
  - 'update'
  - create
- apiGroups:
  - apps
  - batch
  resources:
  - 'replicasets'
  - 'deployments'
  - 'statefulsets'
  - 'jobs'
  - 'cronjobs'
  verbs:
  - 'get'
