apiVersion: datadoghq.com/v1alpha1
kind: DatadogInstrumentation
metadata:
  name: sample-instrumentation
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-workload
  config:
    checks:
      - integration: openmetrics
        containerImage:
          - sample-app
        initConfig: {}
        instances:
          - openmetrics_endpoint: "http://%%host%%:8080/metrics"
            namespace: sample
            metrics:
              - sample_requests_total
            tags:
              - service:sample-app
              - env:dev
        logs:
          - type: file
            path: /var/log/sample-app/*.log
            source: sample-app
            service: sample-app
            tags:
              - service:sample-app
              - env:dev
