apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    clusterAgentToken: <DATADOG_CLUSTER_AGENT_TOKEN>
    clusterName: <CLUSTER_NAME>
    credentials:
      apiKey: <DATADOG_API_KEY>
      appKey: <DATADOG_APP_KEY>
  features:
    admissionController:
      enabled: false
    apm:
      enabled: false
    clusterChecks:
      enabled: false
    cspm:
      enabled: false
    cws:
      enabled: false
    externalMetricsServer:
      enabled: false
    liveProcessCollection:
      enabled: false
    logCollection:
      containerCollectAll: false
      enabled: true
  override:
    clusterAgent:
      replicas: 2
    clusterChecksRunner:
      replicas: 2
