apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  clusterName: <CLUSTER_NAME>
  credentials:
    apiKey: <DATADOG_API_KEY>
    appKey: <DATADOG_APP_KEY>
    token: <DATADOG_CLUSTER_AGENT_TOKEN>
  agent:
    apm:
      enabled: false
    process:
      enabled: true
      processCollection: false
    log:
      enabled: false
      logsConfigContainerCollectAll: false
    systemProbe:
      bpfDebugEnabled: false
    security:
      compliance:
        enabled: false
      runtime:
        enabled: false
  clusterAgent:
    replicas: 2
    config:
      externalMetrics:
        enabled: false
      admissionController:
        enabled: false
      clusterChecksEnabled: false
  clusterChecksRunner:
    replicas: 2
