apiVersion: datadoghq.com/v1alpha1
kind: DatadogMetric
metadata:
  name: datadogmetric-sample
spec:
  query: "avg:kubernetes.cpu.usage.total{app:foo}.rollup(avg,30)/(avg:kubernetes.cpu.limits{app:foo}.rollup(avg,30)*10000000)"
