apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog-agent
spec:
  credentials:
    apiKey: <paste-your-api-key-here>
    appKey: <paste-your-app-key-here>
    token: <paste-your-cluster-agent-token-here>
  agent:
    image: 
      name: "datadog/agent:latest"
    config:
      tolerations:
      - operator: Exists
  clusterAgent:
    image: 
      name: "datadog/cluster-agent:latest"
    config:
      metricsProviderEnabled: true
      clusterChecksRunnerEnabled: true
    replicas: 2
  clusterChecksRunner:
    image: 
      name: "datadog/agent:latest"
