apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog-agent
spec:
  credentials:
    apiKey: <paste-your-api-key-here>
  agent:
    image: 
      name: "datadog/agent:latest"
