apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  credentials:
    apiKey: <DATADOG_API_KEY>
    appKey: <DATADOG_APP_KEY>
    token: <DATADOG_CLUSTER_AGENT_TOKEN>
  agent:
    image:
      name: "datadog/agent:latest"
    config:
      tolerations:
      - operator: Exists
  clusterAgent:
    image:
      name: "datadog/cluster-agent:latest"
    config:
      metricsProviderEnabled: true
      clusterChecksEnabled: true
    replicas: 2
  clusterChecksRunner:
    image:
      name: "datadog/agent:latest"
