apiVersion: datadoghq.com/v1alpha1
kind: ExtendedDaemonSet
metadata:
  name: foo
spec:
  strategy:
    canary:
      replicas: 1
      duration: 5m
    rollingUpdate:
      maxParallelPodCreation: 1
      slowStartIntervalDuration: 1m
  template:
    spec:
      containers:
        - name: daemon
          image: registry.k8s.io/pause:3.0
      tolerations:
        - operator: Exists
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: extendeddaemonset.datadoghq.com/exclude
                    operator: NotIn
                    values:
                      - foo
