# Adds namespace to all resources.
namespace: system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: datadog-operator-

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix including the one in
# crd/kustomization.yaml
# [CERTMANAGER] To enable cert-manager, uncomment all sections with 'CERTMANAGER'. 'WEBHOOK' components are required.
# [PROMETHEUS] To enable prometheus monitor, uncomment all sections with 'PROMETHEUS'.
#- ../prometheus

# [V1alpha1 testing] configure v1alpha1 as the storage version
# This is just in case we need to test something with the old version.
patches:
- path: storagev1_in_datadogagents.yaml
  target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: datadogagents.datadoghq.com
    version: v1
- path: manager_enablev1_patch.yaml
  target:
    group: apps
    kind: Deployment
    name: manager
    namespace: system
    version: v1
- path: manager_webhook_patch.yaml

# Protect the /metrics endpoint by putting it behind auth.
# If you want your controller-manager to expose the /metrics
# endpoint w/o any authn/z, please comment the following line.
#- manager_auth_proxy_patch.yaml

# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix including the one in
# crd/kustomization.yaml

# [CERTMANAGER] To enable cert-manager, uncomment all sections with 'CERTMANAGER'.
# Uncomment 'CERTMANAGER' sections in crd/kustomization.yaml to enable the CA injection in the admission webhooks.
# 'CERTMANAGER' needs to be enabled to use ca injection
#- webhookcainjection_patch.yaml

# the following config is for teaching kustomize how to do var substitution
# [CERTMANAGER] To enable cert-manager, uncomment all sections with 'CERTMANAGER' prefix.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../crd
- ../rbac
- ../manager
- ../webhook
- ../certmanager
replacements:
- source:
    fieldPath: metadata.namespace
    kind: Certificate
    name: serving-cert
- source:
    kind: Certificate
    name: serving-cert
- source:
    fieldPath: metadata.namespace
    kind: Service
    name: webhook-service
  targets:
  - fieldPaths:
    - |-
      spec.# $(SERVICE_NAME) and $(SERVICE_NAMESPACE) will be substituted by kustomize
      dnsNames.0
    options:
      delimiter: .
      index: 1
    select:
      group: cert-manager.io
      kind: Certificate
      name: serving-cert
      namespace: system
      version: v1
  - fieldPaths:
    - |-
      spec.# $(SERVICE_NAME) and $(SERVICE_NAMESPACE) will be substituted by kustomize
      dnsNames.1
    options:
      delimiter: .
      index: 1
    select:
      group: cert-manager.io
      kind: Certificate
      name: serving-cert
      namespace: system
      version: v1
- source:
    kind: Service
    name: webhook-service
  targets:
  - fieldPaths:
    - |-
      spec.# $(SERVICE_NAME) and SERVICE_NAMESPACE_PLACEHOLDER will be substituted by kustomize
      dnsNames.0
    options:
      delimiter: .
    select:
      group: cert-manager.io
      kind: Certificate
      name: serving-cert
      namespace: system
      version: v1
  - fieldPaths:
    - |-
      spec.# $(SERVICE_NAME) and SERVICE_NAMESPACE_PLACEHOLDER will be substituted by kustomize
      dnsNames.1
    options:
      delimiter: .
    select:
      group: cert-manager.io
      kind: Certificate
      name: serving-cert
      namespace: system
      version: v1
