apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Adds namespace to all resources.
namespace: system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: datadog-operator-

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

resources:
- ../crd
- ../rbac
- ../manager
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix including the one in
# crd/kustomization.yaml
#- ../webhook
# [CERTMANAGER] To enable cert-manager, uncomment all sections with 'CERTMANAGER'. 'WEBHOOK' components are required.
#- ../certmanager
# [PROMETHEUS] To enable prometheus monitor, uncomment all sections with 'PROMETHEUS'.
#- ../prometheus

# [V1alpha1 testing] configure v1alpha1 as the storage version
# This is just in case we need to test something with the old version.
#patches:
#- path: storagev1_in_datadogagents.yaml
#  target:
#    group: apiextensions.k8s.io
#    kind: CustomResourceDefinition
#    name: datadogagents.datadoghq.com
#    version: v1
#- path: manager_enablev1_patch.yaml
#  target:
#    group: apps
#    kind: Deployment
#    name: manager
#    namespace: system
#    version: v1

# Protect the /metrics endpoint by putting it behind auth.
# If you want your controller-manager to expose the /metrics
# endpoint w/o any authn/z, please comment the following line.
#- path: manager_auth_proxy_patch.yaml

# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix including the one in
# crd/kustomization.yaml
#- path: manager_webhook_patch.yaml
# [CERTMANAGER] To enable cert-manager, uncomment all sections with 'CERTMANAGER'.
# Uncomment 'CERTMANAGER' sections in crd/kustomization.yaml to enable the CA injection in the admission webhooks.
# 'CERTMANAGER' needs to be enabled to use ca injection
#- path: webhookcainjection_patch.yaml

# the following config is for teaching kustomize how to do var substitution
#replacements:
# [CERTMANAGER] To enable cert-manager, uncomment all sections with 'CERTMANAGER' prefix.
#- source:
#    fieldPath: metadata.namespace
#    kind: Certificate
#    name: serving-cert
#  targets:
#  - fieldPaths:
#    - metadata.annotations.[cert-manager.io/inject-ca-from]
#    options:
#      delimiter: /
#    select: {}
#  - fieldPaths:
#    - metadata.annotations.[cert-manager.io/inject-ca-from]
#    options:
#      delimiter: /
#    select: {}
#- source:
#    kind: Certificate
#    name: serving-cert
#  targets:
#  - fieldPaths:
#    - metadata.annotations.[cert-manager.io/inject-ca-from]
#    options:
#      delimiter: /
#      index: 1
#    select: {}
#  - fieldPaths:
#    - metadata.annotations.[cert-manager.io/inject-ca-from]
#    options:
#      delimiter: /
#      index: 1
#    select: {}
#- source:
#    fieldPath: metadata.namespace
#    kind: Service
#    name: webhook-service
#  targets:
#    - select:
#        kind: Certificate
#        name: serving-cert
#      fieldPaths:
#        - spec.dnsNames.0
#        - spec.dnsNames.1
#- source:
#    fieldPath: metadata.name
#    kind: Service
#    name: webhook-service
#  targets:
#    - select:
#        kind: Certificate
#        name: serving-cert
#      fieldPaths:
#        - spec.dnsNames.0
#        - spec.dnsNames.1
