# Default values for datadog-agent-with-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

agent_spec: |
  credentials:
    apiKey: <DATADOG_API_KEY>
    appKey: <DATADOG_APP_KEY>
  agent:
    image:
      name: "datadog/agent:latest"
    config:
      logLevel: INFO
      tolerations:
      - operator: Exists
      env:
      - name: DD_KUBELET_TLS_VERIFY
        value: "false"
    apm:
      enabled: true
    process:
      enabled: true
    systemProbe:
      enabled: true
  clusterAgent:
    image:
      name: "datadog/cluster-agent:latest"
    config:
      metricsProviderEnabled: true
      clusterChecksEnabled: true
  clusterChecksRunner:
    image:
      name: "datadog/agent:latest"
