# permissions for end users to edit extendeddaemonsetsettings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: extendeddaemonsetsetting-editor-role
rules:
- apiGroups:
  - datadoghq.com
  resources:
  - extendeddaemonsetsettings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - datadoghq.com
  resources:
  - extendeddaemonsetsettings/status
  verbs:
  - get
