# permissions for end users to view extendeddaemonsetsettings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: extendeddaemonsetsetting-viewer-role
rules:
- apiGroups:
  - datadoghq.com
  resources:
  - extendeddaemonsetsettings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - datadoghq.com
  resources:
  - extendeddaemonsetsettings/status
  verbs:
  - get
