# permissions for end users to view extendeddaemonsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: extendeddaemonset-viewer-role
rules:
- apiGroups:
  - datadoghq.com
  resources:
  - extendeddaemonsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - datadoghq.com
  resources:
  - extendeddaemonsets/status
  verbs:
  - get
