# permissions for end users to view extendeddaemonsetreplicasets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: extendeddaemonsetreplicaset-viewer-role
rules:
- apiGroups:
  - datadoghq.com
  resources:
  - extendeddaemonsetreplicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - datadoghq.com
  resources:
  - extendeddaemonsetreplicasets/status
  verbs:
  - get
