# permissions for end users to edit extendeddaemonsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: extendeddaemonset-editor-role
rules:
- apiGroups:
  - datadoghq.com
  resources:
  - extendeddaemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - datadoghq.com
  resources:
  - extendeddaemonsets/status
  verbs:
  - get
