before:
  hooks:
    - go mod download
    - go generate ./...
builds:
- id: kubectl-eds
  goos:
  - windows
  goarch:
  - amd64
  - arm64
  env:
  - CGO_ENABLED=0
  main: ./cmd/kubectl-eds/main.go
  ldflags: -w -X ${BUILDINFOPKG}.Commit=${GIT_COMMIT} -X ${BUILDINFOPKG}.Version=${VERSION} -X ${BUILDINFOPKG}.BuildTime=${DATE} -s
  binary: kubectl-eds
archives:
- id: kubectl-eds
  builds:
  - kubectl-eds
  name_template: "kubectl-eds_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  wrap_in_directory: false
  format: zip
  files:
  - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
