apiVersion: v2
name: operator-eks-addon
version: 0.1.18
appVersion: 0.1.0
description: Datadog Operator Wrapper
home: https://www.datadoghq.com
icon: https://datadog-live.imgix.net/img/dd_logo_70x75.png
maintainers:
- name: Datadog
  email: support@datadoghq.com
dependencies:
- name: datadog-operator
  alias: datadog-operator
  version: 2.13.1
