apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "datadoghq.com/v1alpha1",
          "kind": "ExtendedDaemonSet",
          "metadata": {
            "name": "foo"
          },
          "spec": {
            "strategy": {
              "canary": {
                "duration": "30m",
                "replicas": 2
              },
              "rollingUpdate": {
                "maxParallelPodCreation": 10,
                "slowStartIntervalDuration": "2m"
              }
            },
            "template": {
              "spec": {
                "containers": [
                  {
                    "image": "k8s.gcr.io/pause:3.0",
                    "name": "daemon"
                  }
                ]
              }
            }
          }
        },
        {
          "apiVersion": "datadoghq.com/v1alpha1",
          "kind": "ExtendedDaemonSetReplicaSet",
          "metadata": {
            "name": "automatically-generated-by-extended-daemon-set"
          }
        },
        {
          "apiVersion": "datadoghq.com/v1alpha1",
          "kind": "ExtendedDaemonsetSetting",
          "metadata": {
            "name": "example-extendeddaemonsetsetting"
          },
          "spec": {
            "containers": [
              {
                "name": "daemon",
                "resources": {
                  "requests": {
                    "cpu": "0.1",
                    "memory": "30m"
                  }
                }
              }
            ],
            "nodeSelector": {
              "matchLabels": {
                "overwrite": "foo-daemon"
              }
            },
            "reference": {
              "kind": "ExtendedDaemonset",
              "name": "foo"
            }
          }
        }
      ]
    capabilities: Full Lifecycle
    operators.operatorframework.io/builder: operator-sdk-v1.4.0+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: extendeddaemonset.v0.8.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ExtendedDaemonSetReplicaSet is the Schema for the extendeddaemonsetreplicasets API.
      displayName: Extended Daemon Set Replica Set
      kind: ExtendedDaemonSetReplicaSet
      name: extendeddaemonsetreplicasets.datadoghq.com
      version: v1alpha1
    - description: ExtendedDaemonSet is the Schema for the extendeddaemonsets API.
      displayName: Extended Daemon Set
      kind: ExtendedDaemonSet
      name: extendeddaemonsets.datadoghq.com
      version: v1alpha1
    - description: ExtendedDaemonsetSetting is the Schema for the extendeddaemonsetsettings API.
      displayName: Extended Daemonset Setting
      kind: ExtendedDaemonsetSetting
      name: extendeddaemonsetsettings.datadoghq.com
      version: v1alpha1
  description: |-
    ExtendedDaemonSet aims to provide a new implementation of the Kubernetes DaemonSet resource with key features:
      * Canary Deployment: Deploy a new DaemonSet version with only a few nodes.
      * Custom Rolling Update: Improve the default rolling update logic available in Kubernetes batch/v1 Daemonset.
  displayName: extendeddaemonset
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
        - apiGroups:
          - ""
          resources:
          - nodes
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - podtemplates
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - services
          verbs:
          - get
          - watch
        - apiGroups:
          - datadoghq.com
          resources:
          - extendeddaemonsetreplicasets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - datadoghq.com
          resources:
          - extendeddaemonsetreplicasets/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - datadoghq.com
          resources:
          - extendeddaemonsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - datadoghq.com
          resources:
          - extendeddaemonsets/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - datadoghq.com
          resources:
          - extendeddaemonsetsettings
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - datadoghq.com
          resources:
          - extendeddaemonsetsettings/status
          verbs:
          - get
          - patch
          - update
        serviceAccountName: default
      deployments:
      - name: eds-controller-manager
        spec:
          replicas: 2
          selector:
            matchLabels:
              app.kubernetes.io/name: extendeddaemonset
          strategy: {}
          template:
            metadata:
              labels:
                app.kubernetes.io/name: extendeddaemonset
            spec:
              containers:
              - args:
                - --enable-leader-election
                - --pprof
                command:
                - /manager
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                image: datadog/extendeddaemonset:latest
                imagePullPolicy: Always
                livenessProbe:
                  httpGet:
                    path: /healthz/
                    port: 8081
                  periodSeconds: 10
                name: eds-manager
                ports:
                - containerPort: 8080
                  name: metrics
                  protocol: TCP
                resources:
                  limits:
                    cpu: 100m
                    memory: 100Mi
                  requests:
                    cpu: 100m
                    memory: 100Mi
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - configmaps/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        serviceAccountName: default
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - Daemonset
  - Canary
  - ExtendedDaemonset
  - Deployment
  links:
  - name: Documentation
    url: https://github.com/DataDog/extendeddaemonset
  maintainers:
  - email: cedric@datadoghq.com
    name: Cedric Lamoriniere
  maturity: alpha
  provider:
    name: Datadog
    url: https://github.com/DataDog/extendeddaemonset
  version: 0.8.0
