name: validation
on: [push, pull_request]
env:
  GO111MODULE: "on"
  PROJECTNAME: "extendeddaemonset"
  GO_VERSION: 1.21
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ env.GO_VERSION }}
      id: go
    - name: Install required packages
      uses: mstksg/get-package@v1
      with:
        apt-get: mercurial jq build-essential
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Install tools
      run: |
        make install-tools
    - name: Run build
      run: |
        make manager
    - name: Run unit/control plane tests (fake cluster)
      run: |
        make test
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: cover.out
        flags: unittests
  e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s:
          - v1.14.10
          - v1.16.9
          - v1.18.4
          - v1.21.1
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go
      - name: Install required packages
        uses: mstksg/get-package@v1
        with:
          apt-get: mercurial jq build-essential
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Install tools
        run: |
          make install-tools
      - name: Setup kind for e2e - kube ${{ matrix.k8s }}
        uses: helm/kind-action@v1.2.0
        with:
          config: test/cluster-kind.yaml
          cluster_name: eds-e2e
          wait: 600s
      - name: Run e2e tests - kube ${{ matrix.k8s }}
        run: |
          export PATH=$PATH:$(pwd)/bin
          kubectl cluster-info --context kind-eds-e2e
          kubectl get pods -n kube-system
          make e2e
