---
issuer: https://token.actions.githubusercontent.com

subject: repo:DataDog/datadog-operator:ref:refs/heads/main

claim_pattern:
  event_name: (workflow_dispatch|schedule)
  ref: refs/heads/main
  ref_protected: "true"
  job_workflow_ref: DataDog/datadog-operator/\.github/workflows/stale\.yml@refs/heads/main

permissions:
  actions: write
  issues: write
  pull_requests: write
