issuer: https://token.actions.githubusercontent.com

#WARN: These are inherently never safe against actors with write access, as the permissions become available on all branches
subject: repo:DataDog/datadog-operator:pull_request

claim_pattern:
  event_name: "pull_request"
  job_workflow_ref: DataDog/datadog-operator/\.github/workflows/backport-pr\.yml@.*

permissions:
  contents: write
  pull_requests: write
  issues: write
