apiVersion: datadoghq.com/v1alpha1
kind: ExtendedDaemonSet
metadata:
  name: foo
spec:
  strategy:
    canary:
      replicas: 1
      duration: 5m
      noRestartsDuration: 2m
      autoPause:
        enabled: true
        maxRestarts: 2
      autoFail:
        enabled: true
        maxRestarts: 5
        maxRestartsDuration: 10m
    rollingUpdate:
      maxParallelPodCreation: 1
      maxUnavailable: 2
      slowStartIntervalDuration: 1m
  template:
    spec:
      containers:
        - name: daemon
          image: registry.k8s.io/pause:3.1
          command: ["does", "-not", "-exist"]
      tolerations:
        - operator: Exists
