//go:build !ignore_autogenerated

// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2016-present Datadog, Inc.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/DataDog/datadog-api-client-go/v2/api/datadogV1"
	"github.com/DataDog/datadog-operator/api/datadoghq/common"
	"github.com/DataDog/datadog-operator/api/datadoghq/v2alpha1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config) DeepCopyInto(out *Config) {
	*out = *in
	if in.Override != nil {
		in, out := &in.Override, &out.Override
		*out = make(map[ComponentName]*Override, len(*in))
		for key, val := range *in {
			var outVal *Override
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(Override)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config.
func (in *Config) DeepCopy() *Config {
	if in == nil {
		return nil
	}
	out := new(Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Container) DeepCopyInto(out *Container) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Container.
func (in *Container) DeepCopy() *Container {
	if in == nil {
		return nil
	}
	out := new(Container)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreateStrategy) DeepCopyInto(out *CreateStrategy) {
	*out = *in
	if in.LastTransition != nil {
		in, out := &in.LastTransition, &out.LastTransition
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateStrategy.
func (in *CreateStrategy) DeepCopy() *CreateStrategy {
	if in == nil {
		return nil
	}
	out := new(CreateStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardTemplateVariable) DeepCopyInto(out *DashboardTemplateVariable) {
	*out = *in
	if in.AvailableValues != nil {
		in, out := &in.AvailableValues, &out.AvailableValues
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.Defaults != nil {
		in, out := &in.Defaults, &out.Defaults
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardTemplateVariable.
func (in *DashboardTemplateVariable) DeepCopy() *DashboardTemplateVariable {
	if in == nil {
		return nil
	}
	out := new(DashboardTemplateVariable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardTemplateVariablePreset) DeepCopyInto(out *DashboardTemplateVariablePreset) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.TemplateVariables != nil {
		in, out := &in.TemplateVariables, &out.TemplateVariables
		*out = make([]DashboardTemplateVariablePresetValue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardTemplateVariablePreset.
func (in *DashboardTemplateVariablePreset) DeepCopy() *DashboardTemplateVariablePreset {
	if in == nil {
		return nil
	}
	out := new(DashboardTemplateVariablePreset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardTemplateVariablePresetValue) DeepCopyInto(out *DashboardTemplateVariablePresetValue) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardTemplateVariablePresetValue.
func (in *DashboardTemplateVariablePresetValue) DeepCopy() *DashboardTemplateVariablePresetValue {
	if in == nil {
		return nil
	}
	out := new(DashboardTemplateVariablePresetValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogAgentInternal) DeepCopyInto(out *DatadogAgentInternal) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogAgentInternal.
func (in *DatadogAgentInternal) DeepCopy() *DatadogAgentInternal {
	if in == nil {
		return nil
	}
	out := new(DatadogAgentInternal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatadogAgentInternal) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogAgentInternalList) DeepCopyInto(out *DatadogAgentInternalList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatadogAgentInternal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogAgentInternalList.
func (in *DatadogAgentInternalList) DeepCopy() *DatadogAgentInternalList {
	if in == nil {
		return nil
	}
	out := new(DatadogAgentInternalList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatadogAgentInternalList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogAgentInternalStatus) DeepCopyInto(out *DatadogAgentInternalStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Agent != nil {
		in, out := &in.Agent, &out.Agent
		*out = new(v2alpha1.DaemonSetStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterAgent != nil {
		in, out := &in.ClusterAgent, &out.ClusterAgent
		*out = new(v2alpha1.DeploymentStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterChecksRunner != nil {
		in, out := &in.ClusterChecksRunner, &out.ClusterChecksRunner
		*out = new(v2alpha1.DeploymentStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.RemoteConfigConfiguration != nil {
		in, out := &in.RemoteConfigConfiguration, &out.RemoteConfigConfiguration
		*out = new(v2alpha1.RemoteConfigConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogAgentInternalStatus.
func (in *DatadogAgentInternalStatus) DeepCopy() *DatadogAgentInternalStatus {
	if in == nil {
		return nil
	}
	out := new(DatadogAgentInternalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogAgentProfile) DeepCopyInto(out *DatadogAgentProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogAgentProfile.
func (in *DatadogAgentProfile) DeepCopy() *DatadogAgentProfile {
	if in == nil {
		return nil
	}
	out := new(DatadogAgentProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatadogAgentProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogAgentProfileList) DeepCopyInto(out *DatadogAgentProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatadogAgentProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogAgentProfileList.
func (in *DatadogAgentProfileList) DeepCopy() *DatadogAgentProfileList {
	if in == nil {
		return nil
	}
	out := new(DatadogAgentProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatadogAgentProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogAgentProfileSpec) DeepCopyInto(out *DatadogAgentProfileSpec) {
	*out = *in
	if in.ProfileAffinity != nil {
		in, out := &in.ProfileAffinity, &out.ProfileAffinity
		*out = new(ProfileAffinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(Config)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogAgentProfileSpec.
func (in *DatadogAgentProfileSpec) DeepCopy() *DatadogAgentProfileSpec {
	if in == nil {
		return nil
	}
	out := new(DatadogAgentProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogAgentProfileStatus) DeepCopyInto(out *DatadogAgentProfileStatus) {
	*out = *in
	if in.LastUpdate != nil {
		in, out := &in.LastUpdate, &out.LastUpdate
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CreateStrategy != nil {
		in, out := &in.CreateStrategy, &out.CreateStrategy
		*out = new(CreateStrategy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogAgentProfileStatus.
func (in *DatadogAgentProfileStatus) DeepCopy() *DatadogAgentProfileStatus {
	if in == nil {
		return nil
	}
	out := new(DatadogAgentProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogDashboard) DeepCopyInto(out *DatadogDashboard) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogDashboard.
func (in *DatadogDashboard) DeepCopy() *DatadogDashboard {
	if in == nil {
		return nil
	}
	out := new(DatadogDashboard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatadogDashboard) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogDashboardList) DeepCopyInto(out *DatadogDashboardList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatadogDashboard, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogDashboardList.
func (in *DatadogDashboardList) DeepCopy() *DatadogDashboardList {
	if in == nil {
		return nil
	}
	out := new(DatadogDashboardList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatadogDashboardList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogDashboardSpec) DeepCopyInto(out *DatadogDashboardSpec) {
	*out = *in
	if in.NotifyList != nil {
		in, out := &in.NotifyList, &out.NotifyList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ReflowType != nil {
		in, out := &in.ReflowType, &out.ReflowType
		*out = new(datadogV1.DashboardReflowType)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TemplateVariablePresets != nil {
		in, out := &in.TemplateVariablePresets, &out.TemplateVariablePresets
		*out = make([]DashboardTemplateVariablePreset, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TemplateVariables != nil {
		in, out := &in.TemplateVariables, &out.TemplateVariables
		*out = make([]DashboardTemplateVariable, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogDashboardSpec.
func (in *DatadogDashboardSpec) DeepCopy() *DatadogDashboardSpec {
	if in == nil {
		return nil
	}
	out := new(DatadogDashboardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogDashboardStatus) DeepCopyInto(out *DatadogDashboardStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Created != nil {
		in, out := &in.Created, &out.Created
		*out = (*in).DeepCopy()
	}
	if in.LastForceSyncTime != nil {
		in, out := &in.LastForceSyncTime, &out.LastForceSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogDashboardStatus.
func (in *DatadogDashboardStatus) DeepCopy() *DatadogDashboardStatus {
	if in == nil {
		return nil
	}
	out := new(DatadogDashboardStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogGenericResource) DeepCopyInto(out *DatadogGenericResource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogGenericResource.
func (in *DatadogGenericResource) DeepCopy() *DatadogGenericResource {
	if in == nil {
		return nil
	}
	out := new(DatadogGenericResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatadogGenericResource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogGenericResourceList) DeepCopyInto(out *DatadogGenericResourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatadogGenericResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogGenericResourceList.
func (in *DatadogGenericResourceList) DeepCopy() *DatadogGenericResourceList {
	if in == nil {
		return nil
	}
	out := new(DatadogGenericResourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatadogGenericResourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogGenericResourceSpec) DeepCopyInto(out *DatadogGenericResourceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogGenericResourceSpec.
func (in *DatadogGenericResourceSpec) DeepCopy() *DatadogGenericResourceSpec {
	if in == nil {
		return nil
	}
	out := new(DatadogGenericResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogGenericResourceStatus) DeepCopyInto(out *DatadogGenericResourceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Created != nil {
		in, out := &in.Created, &out.Created
		*out = (*in).DeepCopy()
	}
	if in.LastForceSyncTime != nil {
		in, out := &in.LastForceSyncTime, &out.LastForceSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogGenericResourceStatus.
func (in *DatadogGenericResourceStatus) DeepCopy() *DatadogGenericResourceStatus {
	if in == nil {
		return nil
	}
	out := new(DatadogGenericResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogMetric) DeepCopyInto(out *DatadogMetric) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogMetric.
func (in *DatadogMetric) DeepCopy() *DatadogMetric {
	if in == nil {
		return nil
	}
	out := new(DatadogMetric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatadogMetric) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogMetricCondition) DeepCopyInto(out *DatadogMetricCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogMetricCondition.
func (in *DatadogMetricCondition) DeepCopy() *DatadogMetricCondition {
	if in == nil {
		return nil
	}
	out := new(DatadogMetricCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogMetricList) DeepCopyInto(out *DatadogMetricList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatadogMetric, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogMetricList.
func (in *DatadogMetricList) DeepCopy() *DatadogMetricList {
	if in == nil {
		return nil
	}
	out := new(DatadogMetricList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatadogMetricList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogMetricSpec) DeepCopyInto(out *DatadogMetricSpec) {
	*out = *in
	out.MaxAge = in.MaxAge
	out.TimeWindow = in.TimeWindow
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogMetricSpec.
func (in *DatadogMetricSpec) DeepCopy() *DatadogMetricSpec {
	if in == nil {
		return nil
	}
	out := new(DatadogMetricSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogMetricStatus) DeepCopyInto(out *DatadogMetricStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]DatadogMetricCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogMetricStatus.
func (in *DatadogMetricStatus) DeepCopy() *DatadogMetricStatus {
	if in == nil {
		return nil
	}
	out := new(DatadogMetricStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogMonitor) DeepCopyInto(out *DatadogMonitor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogMonitor.
func (in *DatadogMonitor) DeepCopy() *DatadogMonitor {
	if in == nil {
		return nil
	}
	out := new(DatadogMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatadogMonitor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogMonitorCondition) DeepCopyInto(out *DatadogMonitorCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogMonitorCondition.
func (in *DatadogMonitorCondition) DeepCopy() *DatadogMonitorCondition {
	if in == nil {
		return nil
	}
	out := new(DatadogMonitorCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogMonitorControllerOptions) DeepCopyInto(out *DatadogMonitorControllerOptions) {
	*out = *in
	if in.DisableRequiredTags != nil {
		in, out := &in.DisableRequiredTags, &out.DisableRequiredTags
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogMonitorControllerOptions.
func (in *DatadogMonitorControllerOptions) DeepCopy() *DatadogMonitorControllerOptions {
	if in == nil {
		return nil
	}
	out := new(DatadogMonitorControllerOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogMonitorDowntimeStatus) DeepCopyInto(out *DatadogMonitorDowntimeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogMonitorDowntimeStatus.
func (in *DatadogMonitorDowntimeStatus) DeepCopy() *DatadogMonitorDowntimeStatus {
	if in == nil {
		return nil
	}
	out := new(DatadogMonitorDowntimeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogMonitorList) DeepCopyInto(out *DatadogMonitorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatadogMonitor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogMonitorList.
func (in *DatadogMonitorList) DeepCopy() *DatadogMonitorList {
	if in == nil {
		return nil
	}
	out := new(DatadogMonitorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatadogMonitorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogMonitorOptions) DeepCopyInto(out *DatadogMonitorOptions) {
	*out = *in
	if in.EnableLogsSample != nil {
		in, out := &in.EnableLogsSample, &out.EnableLogsSample
		*out = new(bool)
		**out = **in
	}
	if in.EscalationMessage != nil {
		in, out := &in.EscalationMessage, &out.EscalationMessage
		*out = new(string)
		**out = **in
	}
	if in.EvaluationDelay != nil {
		in, out := &in.EvaluationDelay, &out.EvaluationDelay
		*out = new(int64)
		**out = **in
	}
	if in.IncludeTags != nil {
		in, out := &in.IncludeTags, &out.IncludeTags
		*out = new(bool)
		**out = **in
	}
	if in.GroupbySimpleMonitor != nil {
		in, out := &in.GroupbySimpleMonitor, &out.GroupbySimpleMonitor
		*out = new(bool)
		**out = **in
	}
	if in.Locked != nil {
		in, out := &in.Locked, &out.Locked
		*out = new(bool)
		**out = **in
	}
	if in.NewGroupDelay != nil {
		in, out := &in.NewGroupDelay, &out.NewGroupDelay
		*out = new(int64)
		**out = **in
	}
	if in.NoDataTimeframe != nil {
		in, out := &in.NoDataTimeframe, &out.NoDataTimeframe
		*out = new(int64)
		**out = **in
	}
	if in.NotifyAudit != nil {
		in, out := &in.NotifyAudit, &out.NotifyAudit
		*out = new(bool)
		**out = **in
	}
	if in.NotifyBy != nil {
		in, out := &in.NotifyBy, &out.NotifyBy
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NotifyNoData != nil {
		in, out := &in.NotifyNoData, &out.NotifyNoData
		*out = new(bool)
		**out = **in
	}
	if in.RenotifyInterval != nil {
		in, out := &in.RenotifyInterval, &out.RenotifyInterval
		*out = new(int64)
		**out = **in
	}
	if in.RenotifyOccurrences != nil {
		in, out := &in.RenotifyOccurrences, &out.RenotifyOccurrences
		*out = new(int64)
		**out = **in
	}
	if in.RenotifyStatuses != nil {
		in, out := &in.RenotifyStatuses, &out.RenotifyStatuses
		*out = make([]datadogV1.MonitorRenotifyStatusType, len(*in))
		copy(*out, *in)
	}
	if in.RequireFullWindow != nil {
		in, out := &in.RequireFullWindow, &out.RequireFullWindow
		*out = new(bool)
		**out = **in
	}
	if in.TimeoutH != nil {
		in, out := &in.TimeoutH, &out.TimeoutH
		*out = new(int64)
		**out = **in
	}
	if in.Thresholds != nil {
		in, out := &in.Thresholds, &out.Thresholds
		*out = new(DatadogMonitorOptionsThresholds)
		(*in).DeepCopyInto(*out)
	}
	if in.ThresholdWindows != nil {
		in, out := &in.ThresholdWindows, &out.ThresholdWindows
		*out = new(DatadogMonitorOptionsThresholdWindows)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogMonitorOptions.
func (in *DatadogMonitorOptions) DeepCopy() *DatadogMonitorOptions {
	if in == nil {
		return nil
	}
	out := new(DatadogMonitorOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogMonitorOptionsThresholdWindows) DeepCopyInto(out *DatadogMonitorOptionsThresholdWindows) {
	*out = *in
	if in.RecoveryWindow != nil {
		in, out := &in.RecoveryWindow, &out.RecoveryWindow
		*out = new(string)
		**out = **in
	}
	if in.TriggerWindow != nil {
		in, out := &in.TriggerWindow, &out.TriggerWindow
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogMonitorOptionsThresholdWindows.
func (in *DatadogMonitorOptionsThresholdWindows) DeepCopy() *DatadogMonitorOptionsThresholdWindows {
	if in == nil {
		return nil
	}
	out := new(DatadogMonitorOptionsThresholdWindows)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogMonitorOptionsThresholds) DeepCopyInto(out *DatadogMonitorOptionsThresholds) {
	*out = *in
	if in.Critical != nil {
		in, out := &in.Critical, &out.Critical
		*out = new(string)
		**out = **in
	}
	if in.CriticalRecovery != nil {
		in, out := &in.CriticalRecovery, &out.CriticalRecovery
		*out = new(string)
		**out = **in
	}
	if in.OK != nil {
		in, out := &in.OK, &out.OK
		*out = new(string)
		**out = **in
	}
	if in.Unknown != nil {
		in, out := &in.Unknown, &out.Unknown
		*out = new(string)
		**out = **in
	}
	if in.Warning != nil {
		in, out := &in.Warning, &out.Warning
		*out = new(string)
		**out = **in
	}
	if in.WarningRecovery != nil {
		in, out := &in.WarningRecovery, &out.WarningRecovery
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogMonitorOptionsThresholds.
func (in *DatadogMonitorOptionsThresholds) DeepCopy() *DatadogMonitorOptionsThresholds {
	if in == nil {
		return nil
	}
	out := new(DatadogMonitorOptionsThresholds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogMonitorSpec) DeepCopyInto(out *DatadogMonitorSpec) {
	*out = *in
	if in.RestrictedRoles != nil {
		in, out := &in.RestrictedRoles, &out.RestrictedRoles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Options.DeepCopyInto(&out.Options)
	in.ControllerOptions.DeepCopyInto(&out.ControllerOptions)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogMonitorSpec.
func (in *DatadogMonitorSpec) DeepCopy() *DatadogMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(DatadogMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogMonitorStatus) DeepCopyInto(out *DatadogMonitorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]DatadogMonitorCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Created != nil {
		in, out := &in.Created, &out.Created
		*out = (*in).DeepCopy()
	}
	if in.MonitorLastForceSyncTime != nil {
		in, out := &in.MonitorLastForceSyncTime, &out.MonitorLastForceSyncTime
		*out = (*in).DeepCopy()
	}
	if in.MonitorStateLastUpdateTime != nil {
		in, out := &in.MonitorStateLastUpdateTime, &out.MonitorStateLastUpdateTime
		*out = (*in).DeepCopy()
	}
	if in.MonitorStateLastTransitionTime != nil {
		in, out := &in.MonitorStateLastTransitionTime, &out.MonitorStateLastTransitionTime
		*out = (*in).DeepCopy()
	}
	if in.TriggeredState != nil {
		in, out := &in.TriggeredState, &out.TriggeredState
		*out = make([]DatadogMonitorTriggeredState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.DowntimeStatus = in.DowntimeStatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogMonitorStatus.
func (in *DatadogMonitorStatus) DeepCopy() *DatadogMonitorStatus {
	if in == nil {
		return nil
	}
	out := new(DatadogMonitorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogMonitorTriggeredState) DeepCopyInto(out *DatadogMonitorTriggeredState) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogMonitorTriggeredState.
func (in *DatadogMonitorTriggeredState) DeepCopy() *DatadogMonitorTriggeredState {
	if in == nil {
		return nil
	}
	out := new(DatadogMonitorTriggeredState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscaler) DeepCopyInto(out *DatadogPodAutoscaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscaler.
func (in *DatadogPodAutoscaler) DeepCopy() *DatadogPodAutoscaler {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatadogPodAutoscaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerList) DeepCopyInto(out *DatadogPodAutoscalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatadogPodAutoscaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerList.
func (in *DatadogPodAutoscalerList) DeepCopy() *DatadogPodAutoscalerList {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatadogPodAutoscalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerPolicy) DeepCopyInto(out *DatadogPodAutoscalerPolicy) {
	*out = *in
	if in.Update != nil {
		in, out := &in.Update, &out.Update
		*out = new(common.DatadogPodAutoscalerUpdatePolicy)
		**out = **in
	}
	if in.Upscale != nil {
		in, out := &in.Upscale, &out.Upscale
		*out = new(common.DatadogPodAutoscalerScalingPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Downscale != nil {
		in, out := &in.Downscale, &out.Downscale
		*out = new(common.DatadogPodAutoscalerScalingPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerPolicy.
func (in *DatadogPodAutoscalerPolicy) DeepCopy() *DatadogPodAutoscalerPolicy {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogPodAutoscalerSpec) DeepCopyInto(out *DatadogPodAutoscalerSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	if in.RemoteVersion != nil {
		in, out := &in.RemoteVersion, &out.RemoteVersion
		*out = new(uint64)
		**out = **in
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(DatadogPodAutoscalerPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]common.DatadogPodAutoscalerObjective, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Constraints != nil {
		in, out := &in.Constraints, &out.Constraints
		*out = new(common.DatadogPodAutoscalerConstraints)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogPodAutoscalerSpec.
func (in *DatadogPodAutoscalerSpec) DeepCopy() *DatadogPodAutoscalerSpec {
	if in == nil {
		return nil
	}
	out := new(DatadogPodAutoscalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogSLO) DeepCopyInto(out *DatadogSLO) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogSLO.
func (in *DatadogSLO) DeepCopy() *DatadogSLO {
	if in == nil {
		return nil
	}
	out := new(DatadogSLO)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatadogSLO) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogSLOControllerOptions) DeepCopyInto(out *DatadogSLOControllerOptions) {
	*out = *in
	if in.DisableRequiredTags != nil {
		in, out := &in.DisableRequiredTags, &out.DisableRequiredTags
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogSLOControllerOptions.
func (in *DatadogSLOControllerOptions) DeepCopy() *DatadogSLOControllerOptions {
	if in == nil {
		return nil
	}
	out := new(DatadogSLOControllerOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogSLOList) DeepCopyInto(out *DatadogSLOList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatadogSLO, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogSLOList.
func (in *DatadogSLOList) DeepCopy() *DatadogSLOList {
	if in == nil {
		return nil
	}
	out := new(DatadogSLOList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatadogSLOList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogSLOQuery) DeepCopyInto(out *DatadogSLOQuery) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogSLOQuery.
func (in *DatadogSLOQuery) DeepCopy() *DatadogSLOQuery {
	if in == nil {
		return nil
	}
	out := new(DatadogSLOQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogSLOSpec) DeepCopyInto(out *DatadogSLOSpec) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MonitorIDs != nil {
		in, out := &in.MonitorIDs, &out.MonitorIDs
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Query != nil {
		in, out := &in.Query, &out.Query
		*out = new(DatadogSLOQuery)
		**out = **in
	}
	out.TargetThreshold = in.TargetThreshold.DeepCopy()
	if in.WarningThreshold != nil {
		in, out := &in.WarningThreshold, &out.WarningThreshold
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.ControllerOptions != nil {
		in, out := &in.ControllerOptions, &out.ControllerOptions
		*out = new(DatadogSLOControllerOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogSLOSpec.
func (in *DatadogSLOSpec) DeepCopy() *DatadogSLOSpec {
	if in == nil {
		return nil
	}
	out := new(DatadogSLOSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogSLOStatus) DeepCopyInto(out *DatadogSLOStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Created != nil {
		in, out := &in.Created, &out.Created
		*out = (*in).DeepCopy()
	}
	if in.LastForceSyncTime != nil {
		in, out := &in.LastForceSyncTime, &out.LastForceSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogSLOStatus.
func (in *DatadogSLOStatus) DeepCopy() *DatadogSLOStatus {
	if in == nil {
		return nil
	}
	out := new(DatadogSLOStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Override) DeepCopyInto(out *Override) {
	*out = *in
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make(map[common.AgentContainerName]*Container, len(*in))
		for key, val := range *in {
			var outVal *Container
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(Container)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	if in.PriorityClassName != nil {
		in, out := &in.PriorityClassName, &out.PriorityClassName
		*out = new(string)
		**out = **in
	}
	if in.RuntimeClassName != nil {
		in, out := &in.RuntimeClassName, &out.RuntimeClassName
		*out = new(string)
		**out = **in
	}
	if in.UpdateStrategy != nil {
		in, out := &in.UpdateStrategy, &out.UpdateStrategy
		*out = new(common.UpdateStrategy)
		(*in).DeepCopyInto(*out)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Override.
func (in *Override) DeepCopy() *Override {
	if in == nil {
		return nil
	}
	out := new(Override)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileAffinity) DeepCopyInto(out *ProfileAffinity) {
	*out = *in
	if in.ProfileNodeAffinity != nil {
		in, out := &in.ProfileNodeAffinity, &out.ProfileNodeAffinity
		*out = make([]corev1.NodeSelectorRequirement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileAffinity.
func (in *ProfileAffinity) DeepCopy() *ProfileAffinity {
	if in == nil {
		return nil
	}
	out := new(ProfileAffinity)
	in.DeepCopyInto(out)
	return out
}
