# The following patches adds configure the DatadogAgents CRD to use v2alpha1 as the storage version.
- op: replace
  path: /spec/versions/0/storage
  value: false
- op: replace
  path: /spec/versions/1/storage
  value: true
- op: replace
  path: /spec/versions/1/served
  value: true
