apiVersion: datadoghq.com/v1alpha1
kind: DatadogMonitor
metadata:
  name: datadog-audit-alert-test
  namespace: datadog
spec:
  query: "audits(\"status:error\").rollup(\"cardinality\", \"@usr.id\").last(\"5m\") > 250"
  type: "audit alert"
  name: "Test audit alert made from DatadogMonitor"
  message: "1-2-3 testing"
  tags:
    - "test:datadog"
  priority: 5
  options:
    evaluationDelay: 300
    includeTags: true
    locked: false
    newHostDelay: 300
    notifyNoData: true
    noDataTimeframe: 30
    renotifyInterval: 1440
