# Note: this monitor type requires Datadog Operator v0.8+
apiVersion: datadoghq.com/v1alpha1
kind: DatadogMonitor
metadata:
  name: datadog-event-v2-alert-test
  namespace: datadog
spec:
  query: "events(\"sources:nagios status:(error OR warning) priority:normal\").rollup(\"count\").last(\"1h\") > 10"
  type: "event-v2 alert"
  name: "Test event v2 alert made from DatadogMonitor"
  message: "1-2-3 testing"
  tags:
    - "test:datadog"
  priority: 5
  options:
    evaluationDelay: 300
    includeTags: true
    locked: false
    newGroupDelay: 300
    notifyNoData: true
    noDataTimeframe: 30
    renotifyInterval: 1440
