# Note: this monitor type requires Datadog Operator v0.8+
apiVersion: datadoghq.com/v1alpha1
kind: DatadogMonitor
metadata:
  name: datadog-rum-alert-test
  namespace: datadog
spec:
  query: "rum(\"*\").rollup(\"count\").by(\"@type\").last(\"5m\") >= 5"
  type: "rum alert"
  name: "Test rum alert made from DatadogMonitor"
  message: "1-2-3 testing"
  tags:
    - "test:datadog"
  priority: 5
  options:
    evaluationDelay: 300
    includeTags: true
    locked: false
    newGroupDelay: 300
    notifyNoData: true
    noDataTimeframe: 30
    renotifyInterval: 1440
