name: Backport PR
on:
  pull_request:
    types: [ labeled ]

permissions:
  id-token: write # Required for dd-octo-sts action

jobs:
  backport:
    name: Backport PR
    runs-on: ubuntu-latest
    if: >
        (github.event_name == 'workflow_dispatch' ||
        (github.event.action == 'labeled'
        && contains(github.event.label.name, 'backport/')))
    steps:
      - uses: DataDog/dd-octo-sts-action@acaa02eee7e3bb0839e4272dacb37b8f3b58ba80 # v1.0.3
        id: octo-sts
        with:
          scope: DataDog/datadog-operator
          policy: self.backport-pr.create-pr

      - name: Create backport PR
        uses: tibdex/backport@9565281eda0731b1d20c4025c43339fb0a23812e # v2.0.4
        id: backport
        with:
          label_pattern: "^backport/(?<base>([^ ]+))$"
          labels_template: "<%= JSON.stringify([...labels, 'backport', 'bot', 'qa/skip-qa']) %>"
          github_token: ${{ steps.octo-sts.outputs.token }}
          title_template: "[Backport <%- base %>] <%- title %>"
          body_template: |
            Backport <%- mergeCommitSha %> from #<%- number %>.

            ___

            <%- body %>

      - name: Copy milestone to backport PR
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          BACKPORT_PR: ${{ steps.backport.outputs.created_pull_requests }}
        with:
          github-token: ${{ steps.octo-sts.outputs.token }}
          script: |
            console.log('Raw backport output:', process.env.BACKPORT_PR);

            const orig = context.payload.pull_request;
            if (!orig.milestone) {
              console.log('No milestone to copy.');
              return;
            }
            // Get the milestone number
            const milestoneNumber = orig.milestone.number;
            console.log('Milestone number:', milestoneNumber);

            // Parse the backport PR number from the JSON output
            const backportData = JSON.parse(process.env.BACKPORT_PR);
            const prNumber = Object.values(backportData)[0];
            console.log('Parsed PR number:', prNumber);
            console.log(`Copying milestone ${milestoneNumber} to PR ${prNumber}`);

            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              milestone: milestoneNumber
            });
