name: Backport PR
on:
  pull_request:
    types: [ labeled ]

permissions: {}

jobs:
  backport:
    name: Backport PR
    runs-on: ubuntu-latest
    if: >
        github.event.action == 'labeled'
        && github.event.pull_request.merged_at != null
        && contains(github.event.label.name, 'backport/')
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1.11.6
        id: app-token
        with:
          app-id: ${{ secrets.DD_GITHUBOPS_TOKEN_APP_ID }}
          private-key: ${{ secrets.DD_GITHUBOPS_TOKEN_PRIVATE_KEY }}
      - uses: tibdex/backport@9565281eda0731b1d20c4025c43339fb0a23812e # v2.0.4
        with:
          label_pattern: "^backport/(?<base>([^ ]+))$" 
          labels_template: "<%= JSON.stringify([...labels, 'backport', 'bot']) %>"
          github_token: ${{ steps.app-token.outputs.token }}
          title_template: "[Backport <%- base %>] <%- title %>"
          body_template: |
            Backport <%- mergeCommitSha %> from #<%- number %>.

            ___

            <%- body %>
