name: Backport PR
on:
  pull_request:
    types: [ labeled ]

permissions: {}

jobs:
  backport:
    name: Backport PR
    runs-on: ubuntu-latest
    if: >
        github.event.action == 'labeled'
        && github.event.pull_request.merged_at != null
        && contains(github.event.label.name, 'backport/')
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: tibdex/backport@9565281eda0731b1d20c4025c43339fb0a23812e # v2.0.4
        with:
          label_pattern: "^backport/(?<base>([^ ]+))$" 
          labels_template: "<%= JSON.stringify([...labels, 'backport', 'bot']) %>"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title_template: "[ Backport <%- base %> ] <%- title %>"
          body_template: |
            Backport <%- mergeCommitSha %> from #<%- number %>.

            ___

            <%- body %>
