name: validation
on: [push, pull_request]
# Permission forced by repo-level setting; only elevate on job-level
permissions:
  id-token: write # needed for codecov, allows the action to get a JWT signed by GitHub
  contents: read
  # packages: read
env:
  PROJECTNAME: "datadog-operator"
  GO_VERSION: 1.25.9
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go
      - name: install required packages
        uses: mstksg/get-package@4eda30bb5c6ac62c0f3921dd5884b6ef8fc89ab2 # v1.0.0
        with:
          apt-get: mercurial jq build-essential
      - name: Check out code into the Go module directory
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: install tools
        run: |
          make install-tools
      - name: run build
        run: |
          make manager
      - name: run unit tests and E2E tests (fake cluster)
        run: |
          make test
      - uses: codecov/codecov-action@1af58845a975a7985b0beb0cbe6fbbb71a41dbad # v5.5.3
        with:
          use_oidc: true
          files: cover.out,cover_integration.out
          flags: unittests
      - name: Upload coverage to Datadog
        continue-on-error: true
        uses: DataDog/coverage-upload-github-action@d2cf302a39c05e0ad22063360a2bf6ce0cc4906c # v1
        with:
          api_key: ${{ secrets.DD_API_KEY }}
          files: .
          flags: unittests
