name: publish_community_operators

on: [push]

jobs:
  create-pr-k8s-operatorbub-community-operators:
#    if: startsWith(github.ref, 'refs/tags/v')
#    needs: [ create-release ]
    uses: ./.github/workflows/publish-community-operators-base.yml
    with:
      community_repo: true
      org: k8s-operatorhub
      repo: community-operators

  create-pr-redhat-openshift-ecosystem-community-operators-prod:
#    if: startsWith(github.ref, 'refs/tags/v')
#    needs: [ create-release ]
    uses: ./.github/workflows/publish-community-operators-base.yml
    with:
      community_repo: true
      org: redhat-openshift-ecosystem
      repo: community-operators-prod

  create-pr-redhat-openshift-ecosystem-redhat-marketplace-operators:
#    if: startsWith(github.ref, 'refs/tags/v')
#    needs: [ create-release ]
    uses: ./.github/workflows/publish-community-operators-base.yml
    with:
      community_repo: false
      org: redhat-openshift-ecosystem
      repo: redhat-marketplace-operators

  create-pr-redhat-openshift-ecosystem-certified-operators:
#    if: startsWith(github.ref, 'refs/tags/v')
#    needs: [ create-release ]
    uses: ./.github/workflows/publish-community-operators-base.yml
    with:
      community_repo: false
      org: redhat-openshift-ecosystem
      repo: certified-operators