name: publish_community_operators

on: [push]

jobs:
  k8s-operatorhub--community-operators:
#    if: startsWith(github.ref, 'refs/tags/v')
#    needs: [ create-release ]
    uses: ./.github/workflows/publish-community-operators-base.yml
    with:
      community_repo: true
      org: k8s-operatorhub
      repo: community-operators
      dir: datadog-operator
    secrets:
      GH_ROBOT_TOKEN: ${{secrets.GH_ROBOT_TOKEN}}

  redhat-openshift-ecosystem--community-operators-prod:
#    if: startsWith(github.ref, 'refs/tags/v')
#    needs: [ create-release ]
    uses: ./.github/workflows/publish-community-operators-base.yml
    with:
      community_repo: true
      org: redhat-openshift-ecosystem
      repo: community-operators-prod
      dir: datadog-operator
    secrets:
      GH_ROBOT_TOKEN: ${{secrets.GH_ROBOT_TOKEN}}

  redhat-openshift-ecosystem--redhat-marketplace-operators:
#    if: startsWith(github.ref, 'refs/tags/v')
#    needs: [ create-release ]
    uses: ./.github/workflows/publish-community-operators-base.yml
    with:
      community_repo: false
      org: redhat-openshift-ecosystem
      repo: redhat-marketplace-operators
      dir: datadog-operator-certified-rhmp
    secrets:
      GH_ROBOT_TOKEN: ${{secrets.GH_ROBOT_TOKEN}}

  redhat-openshift-ecosystem--certified-operators:
#    if: startsWith(github.ref, 'refs/tags/v')
#    needs: [ create-release ]
    uses: ./.github/workflows/publish-community-operators-base.yml
    with:
      community_repo: false
      org: redhat-openshift-ecosystem
      repo: certified-operators
      dir: datadog-operator-certified
    secrets:
      GH_ROBOT_TOKEN: ${{secrets.GH_ROBOT_TOKEN}}