name: Release
on:
  push:
    branches:
      - "v[0-9]+.[0-9]+"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"
# Permission forced by repo-level setting; only elevate on job-level
permissions:
  contents: read
  # packages: read
env:
  GO_VERSION: 1.25.9
jobs:
  build-linux-binary:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      # https://github.com/marketplace/actions/goreleaser-action
      contents: write
      # actions/upload-artifact
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: gcc install
        run: sudo apt-get update; sudo apt install gcc-aarch64-linux-gnu
      - name: Get tag
        uses: little-core-labs/get-git-tag@2c292ff564c1a61b989e29f0410d131317f89b03 # v3.0.2
        id: tag
      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Get Latest Release
        id: latest_version
        uses: pozetroninc/github-action-get-latest-release@53d33d213ee71c72360e3c829caf7cee94ec21e2 # master
        with:
          owner: ${{ github.repository_owner }}
          repo: datadog-operator
          excludes: prerelease, draft
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29 # v7.0.0
        with:
          version: 2.4.1
          args: release --skip=publish --config .goreleaser-for-linux.yaml
        env:
          GORELEASER_PREVIOUS_TAG: ${{steps.latest_version.outputs.release}}
      - name: Upload
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: kubectl-datadog-linux
          path: |
            dist/kubectl-datadog_*.zip
            dist/checksums.txt
            dist/CHANGELOG.md
  build-darwin-binary:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: macos-latest
    permissions:
      # https://github.com/marketplace/actions/goreleaser-action
      contents: write
      # actions/upload-artifact
      actions: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Get tag
        uses: little-core-labs/get-git-tag@2c292ff564c1a61b989e29f0410d131317f89b03 # v3.0.2
        id: tag
      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Get Latest Release
        id: latest_version
        uses: pozetroninc/github-action-get-latest-release@53d33d213ee71c72360e3c829caf7cee94ec21e2 # master
        with:
          owner: ${{ github.repository_owner }}
          repo: datadog-operator
          excludes: prerelease, draft
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29 # v7.0.0
        with:
          args: release --skip=publish --config .goreleaser-for-darwin.yaml
        env:
          GORELEASER_PREVIOUS_TAG: ${{steps.latest_version.outputs.release}}
      - name: Upload
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: kubectl-datadog-darwin
          path: |
            dist/kubectl-datadog_*.zip
            dist/checksums.txt
  build-windows-binary:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      # https://github.com/marketplace/actions/goreleaser-action
      contents: write
      # actions/upload-artifact
      actions: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Get tag
        uses: little-core-labs/get-git-tag@2c292ff564c1a61b989e29f0410d131317f89b03 # v3.0.2
        id: tag
      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Get Latest Release
        id: latest_version
        uses: pozetroninc/github-action-get-latest-release@53d33d213ee71c72360e3c829caf7cee94ec21e2 # master
        with:
          owner: ${{ github.repository_owner }}
          repo: datadog-operator
          excludes: prerelease, draft
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29 # v7.0.0
        with:
          args: release --skip=publish --config .goreleaser-for-windows.yaml
        env:
          GORELEASER_PREVIOUS_TAG: ${{steps.latest_version.outputs.release}}
      - name: Upload
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: kubectl-datadog-windows
          path: |
            dist/kubectl-datadog_*.zip
            dist/checksums.txt
  create-release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build-linux-binary, build-darwin-binary, build-windows-binary]
    runs-on: ubuntu-latest
    permissions:
      # https://github.com/marketplace/actions/goreleaser-action
      # https://github.com/softprops/action-gh-release?tab=readme-ov-file#permissions
      contents: write
      # actions/download-artifact
      actions: read
      # Required for getting the OIDC token from GitHub
      id-token: write
    steps:
      - uses: DataDog/dd-octo-sts-action@96a25462dbcb10ebf0bfd6e2ccc917d2ab235b9a # v1.0.4
        id: octo-sts
        with:
          scope: DataDog/datadog-operator
          policy: self.release.create-release
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Make directories
        run: |
          mkdir -p ./dist/linux
          mkdir -p ./dist/darwin
          mkdir -p ./dist/windows
      - name: Download linux binaries
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: kubectl-datadog-linux
          path: ./tmp-build/linux
      - name: Download darwin binaries
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: kubectl-datadog-darwin
          path: ./tmp-build/darwin
      - name: Download windows binaries
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: kubectl-datadog-windows
          path: ./tmp-build/windows
      - name: Get tag
        uses: little-core-labs/get-git-tag@2c292ff564c1a61b989e29f0410d131317f89b03 # v3.0.2
        id: tag
      - name: Prepare ./dist folder
        run: |
          mkdir -p ./dist
          cat ./tmp-build/darwin/checksums.txt >> ./dist/checksums.txt
          cat ./tmp-build/linux/checksums.txt >> ./dist/checksums.txt
          cat ./tmp-build/windows/checksums.txt >> ./dist/checksums.txt
          cp ./tmp-build/linux/CHANGELOG.md dist/CHANGELOG.md
          mv ./tmp-build/darwin/*.zip ./dist
          mv ./tmp-build/linux/*.zip ./dist
          mv ./tmp-build/windows/*.zip ./dist
      - name: Generate Plugin manifest
        run: ./hack/release/generate-plugin-manifest.sh ${{steps.tag.outputs.tag}}
      - name: Release
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2.6.1
        with:
          body_path: dist/CHANGELOG.md
          prerelease: ${{ contains(github.ref, '-rc.') }}
          files: |
            dist/datadog-plugin.yaml
            dist/*.zip
            dist/*.tar.gz
            dist/checksums.txt
        env:
          COMMIT_TAG: ${{steps.tag.outputs.tag}}
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
      - name: Update new plugin version in krew-index
        uses: rajatjindal/krew-release-bot@c970b8a8f6dbc2f2285a26e3ae160903b87002c3 # v0.0.51
        continue-on-error: true
        with:
          krew_template_file: dist/datadog-plugin.yaml
        env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
